// Code generated by go-swagger; DO NOT EDIT.

package cms_block_repository_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCmsBlockRepositoryV1GetByIDGetParams creates a new CmsBlockRepositoryV1GetByIDGetParams object
// with the default values initialized.
func NewCmsBlockRepositoryV1GetByIDGetParams() *CmsBlockRepositoryV1GetByIDGetParams {
	var ()
	return &CmsBlockRepositoryV1GetByIDGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCmsBlockRepositoryV1GetByIDGetParamsWithTimeout creates a new CmsBlockRepositoryV1GetByIDGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCmsBlockRepositoryV1GetByIDGetParamsWithTimeout(timeout time.Duration) *CmsBlockRepositoryV1GetByIDGetParams {
	var ()
	return &CmsBlockRepositoryV1GetByIDGetParams{

		timeout: timeout,
	}
}

// NewCmsBlockRepositoryV1GetByIDGetParamsWithContext creates a new CmsBlockRepositoryV1GetByIDGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewCmsBlockRepositoryV1GetByIDGetParamsWithContext(ctx context.Context) *CmsBlockRepositoryV1GetByIDGetParams {
	var ()
	return &CmsBlockRepositoryV1GetByIDGetParams{

		Context: ctx,
	}
}

// NewCmsBlockRepositoryV1GetByIDGetParamsWithHTTPClient creates a new CmsBlockRepositoryV1GetByIDGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCmsBlockRepositoryV1GetByIDGetParamsWithHTTPClient(client *http.Client) *CmsBlockRepositoryV1GetByIDGetParams {
	var ()
	return &CmsBlockRepositoryV1GetByIDGetParams{
		HTTPClient: client,
	}
}

/*CmsBlockRepositoryV1GetByIDGetParams contains all the parameters to send to the API endpoint
for the cms block repository v1 get by Id get operation typically these are written to a http.Request
*/
type CmsBlockRepositoryV1GetByIDGetParams struct {

	/*BlockID*/
	BlockID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the cms block repository v1 get by Id get params
func (o *CmsBlockRepositoryV1GetByIDGetParams) WithTimeout(timeout time.Duration) *CmsBlockRepositoryV1GetByIDGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cms block repository v1 get by Id get params
func (o *CmsBlockRepositoryV1GetByIDGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cms block repository v1 get by Id get params
func (o *CmsBlockRepositoryV1GetByIDGetParams) WithContext(ctx context.Context) *CmsBlockRepositoryV1GetByIDGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cms block repository v1 get by Id get params
func (o *CmsBlockRepositoryV1GetByIDGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the cms block repository v1 get by Id get params
func (o *CmsBlockRepositoryV1GetByIDGetParams) WithHTTPClient(client *http.Client) *CmsBlockRepositoryV1GetByIDGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the cms block repository v1 get by Id get params
func (o *CmsBlockRepositoryV1GetByIDGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBlockID adds the blockID to the cms block repository v1 get by Id get params
func (o *CmsBlockRepositoryV1GetByIDGetParams) WithBlockID(blockID int64) *CmsBlockRepositoryV1GetByIDGetParams {
	o.SetBlockID(blockID)
	return o
}

// SetBlockID adds the blockId to the cms block repository v1 get by Id get params
func (o *CmsBlockRepositoryV1GetByIDGetParams) SetBlockID(blockID int64) {
	o.BlockID = blockID
}

// WriteToRequest writes these params to a swagger request
func (o *CmsBlockRepositoryV1GetByIDGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param blockId
	if err := r.SetPathParam("blockId", swag.FormatInt64(o.BlockID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
