// Code generated by go-swagger; DO NOT EDIT.

package checkout_guest_payment_information_management_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new checkout guest payment information management v1 API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for checkout guest payment information management v1 API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
CheckoutGuestPaymentInformationManagementV1GetPaymentInformationGet Get payment information
*/
func (a *Client) CheckoutGuestPaymentInformationManagementV1GetPaymentInformationGet(params *CheckoutGuestPaymentInformationManagementV1GetPaymentInformationGetParams) (*CheckoutGuestPaymentInformationManagementV1GetPaymentInformationGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCheckoutGuestPaymentInformationManagementV1GetPaymentInformationGetParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "checkoutGuestPaymentInformationManagementV1GetPaymentInformationGet",
		Method:             "GET",
		PathPattern:        "/V1/guest-carts/{cartId}/payment-information",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &CheckoutGuestPaymentInformationManagementV1GetPaymentInformationGetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*CheckoutGuestPaymentInformationManagementV1GetPaymentInformationGetOK), nil

}

/*
CheckoutGuestPaymentInformationManagementV1SavePaymentInformationAndPlaceOrderPost Set payment information and place order for a specified cart.
*/
func (a *Client) CheckoutGuestPaymentInformationManagementV1SavePaymentInformationAndPlaceOrderPost(params *CheckoutGuestPaymentInformationManagementV1SavePaymentInformationAndPlaceOrderPostParams) (*CheckoutGuestPaymentInformationManagementV1SavePaymentInformationAndPlaceOrderPostOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCheckoutGuestPaymentInformationManagementV1SavePaymentInformationAndPlaceOrderPostParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "checkoutGuestPaymentInformationManagementV1SavePaymentInformationAndPlaceOrderPost",
		Method:             "POST",
		PathPattern:        "/V1/guest-carts/{cartId}/payment-information",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &CheckoutGuestPaymentInformationManagementV1SavePaymentInformationAndPlaceOrderPostReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*CheckoutGuestPaymentInformationManagementV1SavePaymentInformationAndPlaceOrderPostOK), nil

}

/*
CheckoutGuestPaymentInformationManagementV1SavePaymentInformationPost Set payment information for a specified cart.
*/
func (a *Client) CheckoutGuestPaymentInformationManagementV1SavePaymentInformationPost(params *CheckoutGuestPaymentInformationManagementV1SavePaymentInformationPostParams) (*CheckoutGuestPaymentInformationManagementV1SavePaymentInformationPostOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCheckoutGuestPaymentInformationManagementV1SavePaymentInformationPostParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "checkoutGuestPaymentInformationManagementV1SavePaymentInformationPost",
		Method:             "POST",
		PathPattern:        "/V1/guest-carts/{cartId}/set-payment-information",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &CheckoutGuestPaymentInformationManagementV1SavePaymentInformationPostReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*CheckoutGuestPaymentInformationManagementV1SavePaymentInformationPostOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
