// Code generated by go-swagger; DO NOT EDIT.

package company_credit_credit_limit_repository_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "flamingo.me/flamingo-commerce-adapter-magento2/magento2/infrastructure/swaggerclient/models"
)

// CompanyCreditCreditLimitRepositoryV1GetGetReader is a Reader for the CompanyCreditCreditLimitRepositoryV1GetGet structure.
type CompanyCreditCreditLimitRepositoryV1GetGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CompanyCreditCreditLimitRepositoryV1GetGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCompanyCreditCreditLimitRepositoryV1GetGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCompanyCreditCreditLimitRepositoryV1GetGetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewCompanyCreditCreditLimitRepositoryV1GetGetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewCompanyCreditCreditLimitRepositoryV1GetGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCompanyCreditCreditLimitRepositoryV1GetGetOK creates a CompanyCreditCreditLimitRepositoryV1GetGetOK with default headers values
func NewCompanyCreditCreditLimitRepositoryV1GetGetOK() *CompanyCreditCreditLimitRepositoryV1GetGetOK {
	return &CompanyCreditCreditLimitRepositoryV1GetGetOK{}
}

/*CompanyCreditCreditLimitRepositoryV1GetGetOK handles this case with default header values.

200 Success.
*/
type CompanyCreditCreditLimitRepositoryV1GetGetOK struct {
	Payload *models.CompanyCreditDataCreditLimitInterface
}

func (o *CompanyCreditCreditLimitRepositoryV1GetGetOK) Error() string {
	return fmt.Sprintf("[GET /V1/companyCredits/{creditId}][%d] companyCreditCreditLimitRepositoryV1GetGetOK  %+v", 200, o.Payload)
}

func (o *CompanyCreditCreditLimitRepositoryV1GetGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CompanyCreditDataCreditLimitInterface)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCompanyCreditCreditLimitRepositoryV1GetGetBadRequest creates a CompanyCreditCreditLimitRepositoryV1GetGetBadRequest with default headers values
func NewCompanyCreditCreditLimitRepositoryV1GetGetBadRequest() *CompanyCreditCreditLimitRepositoryV1GetGetBadRequest {
	return &CompanyCreditCreditLimitRepositoryV1GetGetBadRequest{}
}

/*CompanyCreditCreditLimitRepositoryV1GetGetBadRequest handles this case with default header values.

400 Bad Request
*/
type CompanyCreditCreditLimitRepositoryV1GetGetBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *CompanyCreditCreditLimitRepositoryV1GetGetBadRequest) Error() string {
	return fmt.Sprintf("[GET /V1/companyCredits/{creditId}][%d] companyCreditCreditLimitRepositoryV1GetGetBadRequest  %+v", 400, o.Payload)
}

func (o *CompanyCreditCreditLimitRepositoryV1GetGetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCompanyCreditCreditLimitRepositoryV1GetGetUnauthorized creates a CompanyCreditCreditLimitRepositoryV1GetGetUnauthorized with default headers values
func NewCompanyCreditCreditLimitRepositoryV1GetGetUnauthorized() *CompanyCreditCreditLimitRepositoryV1GetGetUnauthorized {
	return &CompanyCreditCreditLimitRepositoryV1GetGetUnauthorized{}
}

/*CompanyCreditCreditLimitRepositoryV1GetGetUnauthorized handles this case with default header values.

401 Unauthorized
*/
type CompanyCreditCreditLimitRepositoryV1GetGetUnauthorized struct {
	Payload *models.ErrorResponse
}

func (o *CompanyCreditCreditLimitRepositoryV1GetGetUnauthorized) Error() string {
	return fmt.Sprintf("[GET /V1/companyCredits/{creditId}][%d] companyCreditCreditLimitRepositoryV1GetGetUnauthorized  %+v", 401, o.Payload)
}

func (o *CompanyCreditCreditLimitRepositoryV1GetGetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCompanyCreditCreditLimitRepositoryV1GetGetDefault creates a CompanyCreditCreditLimitRepositoryV1GetGetDefault with default headers values
func NewCompanyCreditCreditLimitRepositoryV1GetGetDefault(code int) *CompanyCreditCreditLimitRepositoryV1GetGetDefault {
	return &CompanyCreditCreditLimitRepositoryV1GetGetDefault{
		_statusCode: code,
	}
}

/*CompanyCreditCreditLimitRepositoryV1GetGetDefault handles this case with default header values.

Unexpected error
*/
type CompanyCreditCreditLimitRepositoryV1GetGetDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the company credit credit limit repository v1 get get default response
func (o *CompanyCreditCreditLimitRepositoryV1GetGetDefault) Code() int {
	return o._statusCode
}

func (o *CompanyCreditCreditLimitRepositoryV1GetGetDefault) Error() string {
	return fmt.Sprintf("[GET /V1/companyCredits/{creditId}][%d] companyCreditCreditLimitRepositoryV1GetGet default  %+v", o._statusCode, o.Payload)
}

func (o *CompanyCreditCreditLimitRepositoryV1GetGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
