// Code generated by go-swagger; DO NOT EDIT.

package quote_guest_billing_address_management_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new quote guest billing address management v1 API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for quote guest billing address management v1 API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
QuoteGuestBillingAddressManagementV1AssignPost Assign a specified billing address to a specified cart.
*/
func (a *Client) QuoteGuestBillingAddressManagementV1AssignPost(params *QuoteGuestBillingAddressManagementV1AssignPostParams) (*QuoteGuestBillingAddressManagementV1AssignPostOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewQuoteGuestBillingAddressManagementV1AssignPostParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "quoteGuestBillingAddressManagementV1AssignPost",
		Method:             "POST",
		PathPattern:        "/V1/guest-carts/{cartId}/billing-address",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &QuoteGuestBillingAddressManagementV1AssignPostReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*QuoteGuestBillingAddressManagementV1AssignPostOK), nil

}

/*
QuoteGuestBillingAddressManagementV1GetGet Return the billing address for a specified quote.
*/
func (a *Client) QuoteGuestBillingAddressManagementV1GetGet(params *QuoteGuestBillingAddressManagementV1GetGetParams) (*QuoteGuestBillingAddressManagementV1GetGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewQuoteGuestBillingAddressManagementV1GetGetParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "quoteGuestBillingAddressManagementV1GetGet",
		Method:             "GET",
		PathPattern:        "/V1/guest-carts/{cartId}/billing-address",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &QuoteGuestBillingAddressManagementV1GetGetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*QuoteGuestBillingAddressManagementV1GetGetOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
