// Code generated by go-swagger; DO NOT EDIT.

package quote_coupon_management_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "flamingo.me/flamingo-commerce-adapter-magento2/magento2/infrastructure/swaggerclient/models"
)

// QuoteCouponManagementV1GetGetReader is a Reader for the QuoteCouponManagementV1GetGet structure.
type QuoteCouponManagementV1GetGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *QuoteCouponManagementV1GetGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewQuoteCouponManagementV1GetGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewQuoteCouponManagementV1GetGetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewQuoteCouponManagementV1GetGetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewQuoteCouponManagementV1GetGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewQuoteCouponManagementV1GetGetOK creates a QuoteCouponManagementV1GetGetOK with default headers values
func NewQuoteCouponManagementV1GetGetOK() *QuoteCouponManagementV1GetGetOK {
	return &QuoteCouponManagementV1GetGetOK{}
}

/*QuoteCouponManagementV1GetGetOK handles this case with default header values.

200 Success.
*/
type QuoteCouponManagementV1GetGetOK struct {
	Payload string
}

func (o *QuoteCouponManagementV1GetGetOK) Error() string {
	return fmt.Sprintf("[GET /V1/carts/{cartId}/coupons][%d] quoteCouponManagementV1GetGetOK  %+v", 200, o.Payload)
}

func (o *QuoteCouponManagementV1GetGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewQuoteCouponManagementV1GetGetBadRequest creates a QuoteCouponManagementV1GetGetBadRequest with default headers values
func NewQuoteCouponManagementV1GetGetBadRequest() *QuoteCouponManagementV1GetGetBadRequest {
	return &QuoteCouponManagementV1GetGetBadRequest{}
}

/*QuoteCouponManagementV1GetGetBadRequest handles this case with default header values.

400 Bad Request
*/
type QuoteCouponManagementV1GetGetBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *QuoteCouponManagementV1GetGetBadRequest) Error() string {
	return fmt.Sprintf("[GET /V1/carts/{cartId}/coupons][%d] quoteCouponManagementV1GetGetBadRequest  %+v", 400, o.Payload)
}

func (o *QuoteCouponManagementV1GetGetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewQuoteCouponManagementV1GetGetUnauthorized creates a QuoteCouponManagementV1GetGetUnauthorized with default headers values
func NewQuoteCouponManagementV1GetGetUnauthorized() *QuoteCouponManagementV1GetGetUnauthorized {
	return &QuoteCouponManagementV1GetGetUnauthorized{}
}

/*QuoteCouponManagementV1GetGetUnauthorized handles this case with default header values.

401 Unauthorized
*/
type QuoteCouponManagementV1GetGetUnauthorized struct {
	Payload *models.ErrorResponse
}

func (o *QuoteCouponManagementV1GetGetUnauthorized) Error() string {
	return fmt.Sprintf("[GET /V1/carts/{cartId}/coupons][%d] quoteCouponManagementV1GetGetUnauthorized  %+v", 401, o.Payload)
}

func (o *QuoteCouponManagementV1GetGetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewQuoteCouponManagementV1GetGetDefault creates a QuoteCouponManagementV1GetGetDefault with default headers values
func NewQuoteCouponManagementV1GetGetDefault(code int) *QuoteCouponManagementV1GetGetDefault {
	return &QuoteCouponManagementV1GetGetDefault{
		_statusCode: code,
	}
}

/*QuoteCouponManagementV1GetGetDefault handles this case with default header values.

Unexpected error
*/
type QuoteCouponManagementV1GetGetDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the quote coupon management v1 get get default response
func (o *QuoteCouponManagementV1GetGetDefault) Code() int {
	return o._statusCode
}

func (o *QuoteCouponManagementV1GetGetDefault) Error() string {
	return fmt.Sprintf("[GET /V1/carts/{cartId}/coupons][%d] quoteCouponManagementV1GetGet default  %+v", o._statusCode, o.Payload)
}

func (o *QuoteCouponManagementV1GetGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
