// Code generated by go-swagger; DO NOT EDIT.

package quote_coupon_management_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewQuoteCouponManagementV1RemoveDeleteMineParams creates a new QuoteCouponManagementV1RemoveDeleteMineParams object
// with the default values initialized.
func NewQuoteCouponManagementV1RemoveDeleteMineParams() *QuoteCouponManagementV1RemoveDeleteMineParams {

	return &QuoteCouponManagementV1RemoveDeleteMineParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewQuoteCouponManagementV1RemoveDeleteMineParamsWithTimeout creates a new QuoteCouponManagementV1RemoveDeleteMineParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewQuoteCouponManagementV1RemoveDeleteMineParamsWithTimeout(timeout time.Duration) *QuoteCouponManagementV1RemoveDeleteMineParams {

	return &QuoteCouponManagementV1RemoveDeleteMineParams{

		timeout: timeout,
	}
}

// NewQuoteCouponManagementV1RemoveDeleteMineParamsWithContext creates a new QuoteCouponManagementV1RemoveDeleteMineParams object
// with the default values initialized, and the ability to set a context for a request
func NewQuoteCouponManagementV1RemoveDeleteMineParamsWithContext(ctx context.Context) *QuoteCouponManagementV1RemoveDeleteMineParams {

	return &QuoteCouponManagementV1RemoveDeleteMineParams{

		Context: ctx,
	}
}

// NewQuoteCouponManagementV1RemoveDeleteMineParamsWithHTTPClient creates a new QuoteCouponManagementV1RemoveDeleteMineParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewQuoteCouponManagementV1RemoveDeleteMineParamsWithHTTPClient(client *http.Client) *QuoteCouponManagementV1RemoveDeleteMineParams {

	return &QuoteCouponManagementV1RemoveDeleteMineParams{
		HTTPClient: client,
	}
}

/*QuoteCouponManagementV1RemoveDeleteMineParams contains all the parameters to send to the API endpoint
for the quote coupon management v1 remove delete mine operation typically these are written to a http.Request
*/
type QuoteCouponManagementV1RemoveDeleteMineParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the quote coupon management v1 remove delete mine params
func (o *QuoteCouponManagementV1RemoveDeleteMineParams) WithTimeout(timeout time.Duration) *QuoteCouponManagementV1RemoveDeleteMineParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the quote coupon management v1 remove delete mine params
func (o *QuoteCouponManagementV1RemoveDeleteMineParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the quote coupon management v1 remove delete mine params
func (o *QuoteCouponManagementV1RemoveDeleteMineParams) WithContext(ctx context.Context) *QuoteCouponManagementV1RemoveDeleteMineParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the quote coupon management v1 remove delete mine params
func (o *QuoteCouponManagementV1RemoveDeleteMineParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the quote coupon management v1 remove delete mine params
func (o *QuoteCouponManagementV1RemoveDeleteMineParams) WithHTTPClient(client *http.Client) *QuoteCouponManagementV1RemoveDeleteMineParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the quote coupon management v1 remove delete mine params
func (o *QuoteCouponManagementV1RemoveDeleteMineParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *QuoteCouponManagementV1RemoveDeleteMineParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
