// Code generated by go-swagger; DO NOT EDIT.

package rma_rma_management_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewRmaRmaManagementV1SaveRmaPutParams creates a new RmaRmaManagementV1SaveRmaPutParams object
// with the default values initialized.
func NewRmaRmaManagementV1SaveRmaPutParams() *RmaRmaManagementV1SaveRmaPutParams {
	var ()
	return &RmaRmaManagementV1SaveRmaPutParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRmaRmaManagementV1SaveRmaPutParamsWithTimeout creates a new RmaRmaManagementV1SaveRmaPutParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRmaRmaManagementV1SaveRmaPutParamsWithTimeout(timeout time.Duration) *RmaRmaManagementV1SaveRmaPutParams {
	var ()
	return &RmaRmaManagementV1SaveRmaPutParams{

		timeout: timeout,
	}
}

// NewRmaRmaManagementV1SaveRmaPutParamsWithContext creates a new RmaRmaManagementV1SaveRmaPutParams object
// with the default values initialized, and the ability to set a context for a request
func NewRmaRmaManagementV1SaveRmaPutParamsWithContext(ctx context.Context) *RmaRmaManagementV1SaveRmaPutParams {
	var ()
	return &RmaRmaManagementV1SaveRmaPutParams{

		Context: ctx,
	}
}

// NewRmaRmaManagementV1SaveRmaPutParamsWithHTTPClient creates a new RmaRmaManagementV1SaveRmaPutParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRmaRmaManagementV1SaveRmaPutParamsWithHTTPClient(client *http.Client) *RmaRmaManagementV1SaveRmaPutParams {
	var ()
	return &RmaRmaManagementV1SaveRmaPutParams{
		HTTPClient: client,
	}
}

/*RmaRmaManagementV1SaveRmaPutParams contains all the parameters to send to the API endpoint
for the rma rma management v1 save rma put operation typically these are written to a http.Request
*/
type RmaRmaManagementV1SaveRmaPutParams struct {

	/*ID*/
	ID string
	/*RmaRmaManagementV1SaveRmaPutBody*/
	RmaRmaManagementV1SaveRmaPutBody RmaRmaManagementV1SaveRmaPutBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the rma rma management v1 save rma put params
func (o *RmaRmaManagementV1SaveRmaPutParams) WithTimeout(timeout time.Duration) *RmaRmaManagementV1SaveRmaPutParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the rma rma management v1 save rma put params
func (o *RmaRmaManagementV1SaveRmaPutParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the rma rma management v1 save rma put params
func (o *RmaRmaManagementV1SaveRmaPutParams) WithContext(ctx context.Context) *RmaRmaManagementV1SaveRmaPutParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the rma rma management v1 save rma put params
func (o *RmaRmaManagementV1SaveRmaPutParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the rma rma management v1 save rma put params
func (o *RmaRmaManagementV1SaveRmaPutParams) WithHTTPClient(client *http.Client) *RmaRmaManagementV1SaveRmaPutParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the rma rma management v1 save rma put params
func (o *RmaRmaManagementV1SaveRmaPutParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the rma rma management v1 save rma put params
func (o *RmaRmaManagementV1SaveRmaPutParams) WithID(id string) *RmaRmaManagementV1SaveRmaPutParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the rma rma management v1 save rma put params
func (o *RmaRmaManagementV1SaveRmaPutParams) SetID(id string) {
	o.ID = id
}

// WithRmaRmaManagementV1SaveRmaPutBody adds the rmaRmaManagementV1SaveRmaPutBody to the rma rma management v1 save rma put params
func (o *RmaRmaManagementV1SaveRmaPutParams) WithRmaRmaManagementV1SaveRmaPutBody(rmaRmaManagementV1SaveRmaPutBody RmaRmaManagementV1SaveRmaPutBody) *RmaRmaManagementV1SaveRmaPutParams {
	o.SetRmaRmaManagementV1SaveRmaPutBody(rmaRmaManagementV1SaveRmaPutBody)
	return o
}

// SetRmaRmaManagementV1SaveRmaPutBody adds the rmaRmaManagementV1SaveRmaPutBody to the rma rma management v1 save rma put params
func (o *RmaRmaManagementV1SaveRmaPutParams) SetRmaRmaManagementV1SaveRmaPutBody(rmaRmaManagementV1SaveRmaPutBody RmaRmaManagementV1SaveRmaPutBody) {
	o.RmaRmaManagementV1SaveRmaPutBody = rmaRmaManagementV1SaveRmaPutBody
}

// WriteToRequest writes these params to a swagger request
func (o *RmaRmaManagementV1SaveRmaPutParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.RmaRmaManagementV1SaveRmaPutBody); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
