// Code generated by go-swagger; DO NOT EDIT.

package checkout_shipping_information_management_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new checkout shipping information management v1 API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for checkout shipping information management v1 API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
CheckoutShippingInformationManagementV1SaveAddressInformationPost checkout shipping information management v1 save address information post API
*/
func (a *Client) CheckoutShippingInformationManagementV1SaveAddressInformationPost(params *CheckoutShippingInformationManagementV1SaveAddressInformationPostParams) (*CheckoutShippingInformationManagementV1SaveAddressInformationPostOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCheckoutShippingInformationManagementV1SaveAddressInformationPostParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "checkoutShippingInformationManagementV1SaveAddressInformationPost",
		Method:             "POST",
		PathPattern:        "/V1/carts/{cartId}/shipping-information",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &CheckoutShippingInformationManagementV1SaveAddressInformationPostReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*CheckoutShippingInformationManagementV1SaveAddressInformationPostOK), nil

}

/*
CheckoutShippingInformationManagementV1SaveAddressInformationPostMine checkout shipping information management v1 save address information post mine API
*/
func (a *Client) CheckoutShippingInformationManagementV1SaveAddressInformationPostMine(params *CheckoutShippingInformationManagementV1SaveAddressInformationPostMineParams) (*CheckoutShippingInformationManagementV1SaveAddressInformationPostMineOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCheckoutShippingInformationManagementV1SaveAddressInformationPostMineParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "checkoutShippingInformationManagementV1SaveAddressInformationPostMine",
		Method:             "POST",
		PathPattern:        "/V1/carts/mine/shipping-information",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &CheckoutShippingInformationManagementV1SaveAddressInformationPostMineReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*CheckoutShippingInformationManagementV1SaveAddressInformationPostMineOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
