// Code generated by go-swagger; DO NOT EDIT.

package quote_cart_total_repository_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new quote cart total repository v1 API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for quote cart total repository v1 API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
QuoteCartTotalRepositoryV1GetGet Returns quote totals data for a specified cart.
*/
func (a *Client) QuoteCartTotalRepositoryV1GetGet(params *QuoteCartTotalRepositoryV1GetGetParams) (*QuoteCartTotalRepositoryV1GetGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewQuoteCartTotalRepositoryV1GetGetParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "quoteCartTotalRepositoryV1GetGet",
		Method:             "GET",
		PathPattern:        "/V1/carts/{cartId}/totals",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &QuoteCartTotalRepositoryV1GetGetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*QuoteCartTotalRepositoryV1GetGetOK), nil

}

/*
QuoteCartTotalRepositoryV1GetGetMine Returns quote totals data for a specified cart.
*/
func (a *Client) QuoteCartTotalRepositoryV1GetGetMine(params *QuoteCartTotalRepositoryV1GetGetMineParams) (*QuoteCartTotalRepositoryV1GetGetMineOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewQuoteCartTotalRepositoryV1GetGetMineParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "quoteCartTotalRepositoryV1GetGetMine",
		Method:             "GET",
		PathPattern:        "/V1/carts/mine/totals",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &QuoteCartTotalRepositoryV1GetGetMineReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*QuoteCartTotalRepositoryV1GetGetMineOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
