// Code generated by go-swagger; DO NOT EDIT.

package gift_registry_guest_cart_shipping_method_management_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	models "flamingo.me/flamingo-commerce-adapter-magento2/magento2/infrastructure/swaggerclient/models"
)

// GiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostReader is a Reader for the GiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPost structure.
type GiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewGiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostOK creates a GiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostOK with default headers values
func NewGiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostOK() *GiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostOK {
	return &GiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostOK{}
}

/*GiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostOK handles this case with default header values.

200 Success.
*/
type GiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostOK struct {
	Payload []*models.QuoteDataShippingMethodInterface
}

func (o *GiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostOK) Error() string {
	return fmt.Sprintf("[POST /V1/guest-giftregistry/{cartId}/estimate-shipping-methods][%d] giftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIdPostOK  %+v", 200, o.Payload)
}

func (o *GiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostBadRequest creates a GiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostBadRequest with default headers values
func NewGiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostBadRequest() *GiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostBadRequest {
	return &GiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostBadRequest{}
}

/*GiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostBadRequest handles this case with default header values.

400 Bad Request
*/
type GiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *GiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostBadRequest) Error() string {
	return fmt.Sprintf("[POST /V1/guest-giftregistry/{cartId}/estimate-shipping-methods][%d] giftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIdPostBadRequest  %+v", 400, o.Payload)
}

func (o *GiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostDefault creates a GiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostDefault with default headers values
func NewGiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostDefault(code int) *GiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostDefault {
	return &GiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostDefault{
		_statusCode: code,
	}
}

/*GiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostDefault handles this case with default header values.

Unexpected error
*/
type GiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the gift registry guest cart shipping method management v1 estimate by registry Id post default response
func (o *GiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostDefault) Code() int {
	return o._statusCode
}

func (o *GiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostDefault) Error() string {
	return fmt.Sprintf("[POST /V1/guest-giftregistry/{cartId}/estimate-shipping-methods][%d] giftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIdPost default  %+v", o._statusCode, o.Payload)
}

func (o *GiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostBody gift registry guest cart shipping method management v1 estimate by registry ID post body
swagger:model GiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostBody
*/
type GiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostBody struct {

	// The estimate registry id
	// Required: true
	RegistryID *int64 `json:"registryId"`
}

// Validate validates this gift registry guest cart shipping method management v1 estimate by registry ID post body
func (o *GiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateRegistryID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostBody) validateRegistryID(formats strfmt.Registry) error {

	if err := validate.Required("giftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIdPostBody"+"."+"registryId", "body", o.RegistryID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostBody) UnmarshalBinary(b []byte) error {
	var res GiftRegistryGuestCartShippingMethodManagementV1EstimateByRegistryIDPostBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
