// Code generated by go-swagger; DO NOT EDIT.

package quote_guest_payment_method_management_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	models "flamingo.me/flamingo-commerce-adapter-magento2/magento2/infrastructure/swaggerclient/models"
)

// QuoteGuestPaymentMethodManagementV1SetPutReader is a Reader for the QuoteGuestPaymentMethodManagementV1SetPut structure.
type QuoteGuestPaymentMethodManagementV1SetPutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *QuoteGuestPaymentMethodManagementV1SetPutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewQuoteGuestPaymentMethodManagementV1SetPutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewQuoteGuestPaymentMethodManagementV1SetPutBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewQuoteGuestPaymentMethodManagementV1SetPutDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewQuoteGuestPaymentMethodManagementV1SetPutOK creates a QuoteGuestPaymentMethodManagementV1SetPutOK with default headers values
func NewQuoteGuestPaymentMethodManagementV1SetPutOK() *QuoteGuestPaymentMethodManagementV1SetPutOK {
	return &QuoteGuestPaymentMethodManagementV1SetPutOK{}
}

/*QuoteGuestPaymentMethodManagementV1SetPutOK handles this case with default header values.

200 Success.
*/
type QuoteGuestPaymentMethodManagementV1SetPutOK struct {
	Payload int64
}

func (o *QuoteGuestPaymentMethodManagementV1SetPutOK) Error() string {
	return fmt.Sprintf("[PUT /V1/guest-carts/{cartId}/selected-payment-method][%d] quoteGuestPaymentMethodManagementV1SetPutOK  %+v", 200, o.Payload)
}

func (o *QuoteGuestPaymentMethodManagementV1SetPutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewQuoteGuestPaymentMethodManagementV1SetPutBadRequest creates a QuoteGuestPaymentMethodManagementV1SetPutBadRequest with default headers values
func NewQuoteGuestPaymentMethodManagementV1SetPutBadRequest() *QuoteGuestPaymentMethodManagementV1SetPutBadRequest {
	return &QuoteGuestPaymentMethodManagementV1SetPutBadRequest{}
}

/*QuoteGuestPaymentMethodManagementV1SetPutBadRequest handles this case with default header values.

400 Bad Request
*/
type QuoteGuestPaymentMethodManagementV1SetPutBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *QuoteGuestPaymentMethodManagementV1SetPutBadRequest) Error() string {
	return fmt.Sprintf("[PUT /V1/guest-carts/{cartId}/selected-payment-method][%d] quoteGuestPaymentMethodManagementV1SetPutBadRequest  %+v", 400, o.Payload)
}

func (o *QuoteGuestPaymentMethodManagementV1SetPutBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewQuoteGuestPaymentMethodManagementV1SetPutDefault creates a QuoteGuestPaymentMethodManagementV1SetPutDefault with default headers values
func NewQuoteGuestPaymentMethodManagementV1SetPutDefault(code int) *QuoteGuestPaymentMethodManagementV1SetPutDefault {
	return &QuoteGuestPaymentMethodManagementV1SetPutDefault{
		_statusCode: code,
	}
}

/*QuoteGuestPaymentMethodManagementV1SetPutDefault handles this case with default header values.

Unexpected error
*/
type QuoteGuestPaymentMethodManagementV1SetPutDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the quote guest payment method management v1 set put default response
func (o *QuoteGuestPaymentMethodManagementV1SetPutDefault) Code() int {
	return o._statusCode
}

func (o *QuoteGuestPaymentMethodManagementV1SetPutDefault) Error() string {
	return fmt.Sprintf("[PUT /V1/guest-carts/{cartId}/selected-payment-method][%d] quoteGuestPaymentMethodManagementV1SetPut default  %+v", o._statusCode, o.Payload)
}

func (o *QuoteGuestPaymentMethodManagementV1SetPutDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*QuoteGuestPaymentMethodManagementV1SetPutBody quote guest payment method management v1 set put body
swagger:model QuoteGuestPaymentMethodManagementV1SetPutBody
*/
type QuoteGuestPaymentMethodManagementV1SetPutBody struct {

	// method
	// Required: true
	Method *models.QuoteDataPaymentInterface `json:"method"`
}

// Validate validates this quote guest payment method management v1 set put body
func (o *QuoteGuestPaymentMethodManagementV1SetPutBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMethod(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *QuoteGuestPaymentMethodManagementV1SetPutBody) validateMethod(formats strfmt.Registry) error {

	if err := validate.Required("quoteGuestPaymentMethodManagementV1SetPutBody"+"."+"method", "body", o.Method); err != nil {
		return err
	}

	if o.Method != nil {
		if err := o.Method.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("quoteGuestPaymentMethodManagementV1SetPutBody" + "." + "method")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *QuoteGuestPaymentMethodManagementV1SetPutBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *QuoteGuestPaymentMethodManagementV1SetPutBody) UnmarshalBinary(b []byte) error {
	var res QuoteGuestPaymentMethodManagementV1SetPutBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
