// Code generated by go-swagger; DO NOT EDIT.

package configurable_product_link_management_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewConfigurableProductLinkManagementV1AddChildPostParams creates a new ConfigurableProductLinkManagementV1AddChildPostParams object
// with the default values initialized.
func NewConfigurableProductLinkManagementV1AddChildPostParams() *ConfigurableProductLinkManagementV1AddChildPostParams {
	var ()
	return &ConfigurableProductLinkManagementV1AddChildPostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewConfigurableProductLinkManagementV1AddChildPostParamsWithTimeout creates a new ConfigurableProductLinkManagementV1AddChildPostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewConfigurableProductLinkManagementV1AddChildPostParamsWithTimeout(timeout time.Duration) *ConfigurableProductLinkManagementV1AddChildPostParams {
	var ()
	return &ConfigurableProductLinkManagementV1AddChildPostParams{

		timeout: timeout,
	}
}

// NewConfigurableProductLinkManagementV1AddChildPostParamsWithContext creates a new ConfigurableProductLinkManagementV1AddChildPostParams object
// with the default values initialized, and the ability to set a context for a request
func NewConfigurableProductLinkManagementV1AddChildPostParamsWithContext(ctx context.Context) *ConfigurableProductLinkManagementV1AddChildPostParams {
	var ()
	return &ConfigurableProductLinkManagementV1AddChildPostParams{

		Context: ctx,
	}
}

// NewConfigurableProductLinkManagementV1AddChildPostParamsWithHTTPClient creates a new ConfigurableProductLinkManagementV1AddChildPostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewConfigurableProductLinkManagementV1AddChildPostParamsWithHTTPClient(client *http.Client) *ConfigurableProductLinkManagementV1AddChildPostParams {
	var ()
	return &ConfigurableProductLinkManagementV1AddChildPostParams{
		HTTPClient: client,
	}
}

/*ConfigurableProductLinkManagementV1AddChildPostParams contains all the parameters to send to the API endpoint
for the configurable product link management v1 add child post operation typically these are written to a http.Request
*/
type ConfigurableProductLinkManagementV1AddChildPostParams struct {

	/*ConfigurableProductLinkManagementV1AddChildPostBody*/
	ConfigurableProductLinkManagementV1AddChildPostBody ConfigurableProductLinkManagementV1AddChildPostBody
	/*Sku*/
	Sku string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the configurable product link management v1 add child post params
func (o *ConfigurableProductLinkManagementV1AddChildPostParams) WithTimeout(timeout time.Duration) *ConfigurableProductLinkManagementV1AddChildPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the configurable product link management v1 add child post params
func (o *ConfigurableProductLinkManagementV1AddChildPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the configurable product link management v1 add child post params
func (o *ConfigurableProductLinkManagementV1AddChildPostParams) WithContext(ctx context.Context) *ConfigurableProductLinkManagementV1AddChildPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the configurable product link management v1 add child post params
func (o *ConfigurableProductLinkManagementV1AddChildPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the configurable product link management v1 add child post params
func (o *ConfigurableProductLinkManagementV1AddChildPostParams) WithHTTPClient(client *http.Client) *ConfigurableProductLinkManagementV1AddChildPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the configurable product link management v1 add child post params
func (o *ConfigurableProductLinkManagementV1AddChildPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithConfigurableProductLinkManagementV1AddChildPostBody adds the configurableProductLinkManagementV1AddChildPostBody to the configurable product link management v1 add child post params
func (o *ConfigurableProductLinkManagementV1AddChildPostParams) WithConfigurableProductLinkManagementV1AddChildPostBody(configurableProductLinkManagementV1AddChildPostBody ConfigurableProductLinkManagementV1AddChildPostBody) *ConfigurableProductLinkManagementV1AddChildPostParams {
	o.SetConfigurableProductLinkManagementV1AddChildPostBody(configurableProductLinkManagementV1AddChildPostBody)
	return o
}

// SetConfigurableProductLinkManagementV1AddChildPostBody adds the configurableProductLinkManagementV1AddChildPostBody to the configurable product link management v1 add child post params
func (o *ConfigurableProductLinkManagementV1AddChildPostParams) SetConfigurableProductLinkManagementV1AddChildPostBody(configurableProductLinkManagementV1AddChildPostBody ConfigurableProductLinkManagementV1AddChildPostBody) {
	o.ConfigurableProductLinkManagementV1AddChildPostBody = configurableProductLinkManagementV1AddChildPostBody
}

// WithSku adds the sku to the configurable product link management v1 add child post params
func (o *ConfigurableProductLinkManagementV1AddChildPostParams) WithSku(sku string) *ConfigurableProductLinkManagementV1AddChildPostParams {
	o.SetSku(sku)
	return o
}

// SetSku adds the sku to the configurable product link management v1 add child post params
func (o *ConfigurableProductLinkManagementV1AddChildPostParams) SetSku(sku string) {
	o.Sku = sku
}

// WriteToRequest writes these params to a swagger request
func (o *ConfigurableProductLinkManagementV1AddChildPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.ConfigurableProductLinkManagementV1AddChildPostBody); err != nil {
		return err
	}

	// path param sku
	if err := r.SetPathParam("sku", o.Sku); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
