// Code generated by go-swagger; DO NOT EDIT.

package sales_invoice_management_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSalesInvoiceManagementV1NotifyPostParams creates a new SalesInvoiceManagementV1NotifyPostParams object
// with the default values initialized.
func NewSalesInvoiceManagementV1NotifyPostParams() *SalesInvoiceManagementV1NotifyPostParams {
	var ()
	return &SalesInvoiceManagementV1NotifyPostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSalesInvoiceManagementV1NotifyPostParamsWithTimeout creates a new SalesInvoiceManagementV1NotifyPostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSalesInvoiceManagementV1NotifyPostParamsWithTimeout(timeout time.Duration) *SalesInvoiceManagementV1NotifyPostParams {
	var ()
	return &SalesInvoiceManagementV1NotifyPostParams{

		timeout: timeout,
	}
}

// NewSalesInvoiceManagementV1NotifyPostParamsWithContext creates a new SalesInvoiceManagementV1NotifyPostParams object
// with the default values initialized, and the ability to set a context for a request
func NewSalesInvoiceManagementV1NotifyPostParamsWithContext(ctx context.Context) *SalesInvoiceManagementV1NotifyPostParams {
	var ()
	return &SalesInvoiceManagementV1NotifyPostParams{

		Context: ctx,
	}
}

// NewSalesInvoiceManagementV1NotifyPostParamsWithHTTPClient creates a new SalesInvoiceManagementV1NotifyPostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSalesInvoiceManagementV1NotifyPostParamsWithHTTPClient(client *http.Client) *SalesInvoiceManagementV1NotifyPostParams {
	var ()
	return &SalesInvoiceManagementV1NotifyPostParams{
		HTTPClient: client,
	}
}

/*SalesInvoiceManagementV1NotifyPostParams contains all the parameters to send to the API endpoint
for the sales invoice management v1 notify post operation typically these are written to a http.Request
*/
type SalesInvoiceManagementV1NotifyPostParams struct {

	/*ID
	  The invoice ID.

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the sales invoice management v1 notify post params
func (o *SalesInvoiceManagementV1NotifyPostParams) WithTimeout(timeout time.Duration) *SalesInvoiceManagementV1NotifyPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the sales invoice management v1 notify post params
func (o *SalesInvoiceManagementV1NotifyPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the sales invoice management v1 notify post params
func (o *SalesInvoiceManagementV1NotifyPostParams) WithContext(ctx context.Context) *SalesInvoiceManagementV1NotifyPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the sales invoice management v1 notify post params
func (o *SalesInvoiceManagementV1NotifyPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the sales invoice management v1 notify post params
func (o *SalesInvoiceManagementV1NotifyPostParams) WithHTTPClient(client *http.Client) *SalesInvoiceManagementV1NotifyPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the sales invoice management v1 notify post params
func (o *SalesInvoiceManagementV1NotifyPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the sales invoice management v1 notify post params
func (o *SalesInvoiceManagementV1NotifyPostParams) WithID(id int64) *SalesInvoiceManagementV1NotifyPostParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the sales invoice management v1 notify post params
func (o *SalesInvoiceManagementV1NotifyPostParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *SalesInvoiceManagementV1NotifyPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
