// Code generated by go-swagger; DO NOT EDIT.

package bundle_product_option_repository_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewBundleProductOptionRepositoryV1GetGetParams creates a new BundleProductOptionRepositoryV1GetGetParams object
// with the default values initialized.
func NewBundleProductOptionRepositoryV1GetGetParams() *BundleProductOptionRepositoryV1GetGetParams {
	var ()
	return &BundleProductOptionRepositoryV1GetGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewBundleProductOptionRepositoryV1GetGetParamsWithTimeout creates a new BundleProductOptionRepositoryV1GetGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewBundleProductOptionRepositoryV1GetGetParamsWithTimeout(timeout time.Duration) *BundleProductOptionRepositoryV1GetGetParams {
	var ()
	return &BundleProductOptionRepositoryV1GetGetParams{

		timeout: timeout,
	}
}

// NewBundleProductOptionRepositoryV1GetGetParamsWithContext creates a new BundleProductOptionRepositoryV1GetGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewBundleProductOptionRepositoryV1GetGetParamsWithContext(ctx context.Context) *BundleProductOptionRepositoryV1GetGetParams {
	var ()
	return &BundleProductOptionRepositoryV1GetGetParams{

		Context: ctx,
	}
}

// NewBundleProductOptionRepositoryV1GetGetParamsWithHTTPClient creates a new BundleProductOptionRepositoryV1GetGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewBundleProductOptionRepositoryV1GetGetParamsWithHTTPClient(client *http.Client) *BundleProductOptionRepositoryV1GetGetParams {
	var ()
	return &BundleProductOptionRepositoryV1GetGetParams{
		HTTPClient: client,
	}
}

/*BundleProductOptionRepositoryV1GetGetParams contains all the parameters to send to the API endpoint
for the bundle product option repository v1 get get operation typically these are written to a http.Request
*/
type BundleProductOptionRepositoryV1GetGetParams struct {

	/*OptionID*/
	OptionID int64
	/*Sku*/
	Sku string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the bundle product option repository v1 get get params
func (o *BundleProductOptionRepositoryV1GetGetParams) WithTimeout(timeout time.Duration) *BundleProductOptionRepositoryV1GetGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the bundle product option repository v1 get get params
func (o *BundleProductOptionRepositoryV1GetGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the bundle product option repository v1 get get params
func (o *BundleProductOptionRepositoryV1GetGetParams) WithContext(ctx context.Context) *BundleProductOptionRepositoryV1GetGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the bundle product option repository v1 get get params
func (o *BundleProductOptionRepositoryV1GetGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the bundle product option repository v1 get get params
func (o *BundleProductOptionRepositoryV1GetGetParams) WithHTTPClient(client *http.Client) *BundleProductOptionRepositoryV1GetGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the bundle product option repository v1 get get params
func (o *BundleProductOptionRepositoryV1GetGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOptionID adds the optionID to the bundle product option repository v1 get get params
func (o *BundleProductOptionRepositoryV1GetGetParams) WithOptionID(optionID int64) *BundleProductOptionRepositoryV1GetGetParams {
	o.SetOptionID(optionID)
	return o
}

// SetOptionID adds the optionId to the bundle product option repository v1 get get params
func (o *BundleProductOptionRepositoryV1GetGetParams) SetOptionID(optionID int64) {
	o.OptionID = optionID
}

// WithSku adds the sku to the bundle product option repository v1 get get params
func (o *BundleProductOptionRepositoryV1GetGetParams) WithSku(sku string) *BundleProductOptionRepositoryV1GetGetParams {
	o.SetSku(sku)
	return o
}

// SetSku adds the sku to the bundle product option repository v1 get get params
func (o *BundleProductOptionRepositoryV1GetGetParams) SetSku(sku string) {
	o.Sku = sku
}

// WriteToRequest writes these params to a swagger request
func (o *BundleProductOptionRepositoryV1GetGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param optionId
	if err := r.SetPathParam("optionId", swag.FormatInt64(o.OptionID)); err != nil {
		return err
	}

	// path param sku
	if err := r.SetPathParam("sku", o.Sku); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
