// Code generated by go-swagger; DO NOT EDIT.

package sales_order_item_repository_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSalesOrderItemRepositoryV1GetGetParams creates a new SalesOrderItemRepositoryV1GetGetParams object
// with the default values initialized.
func NewSalesOrderItemRepositoryV1GetGetParams() *SalesOrderItemRepositoryV1GetGetParams {
	var ()
	return &SalesOrderItemRepositoryV1GetGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSalesOrderItemRepositoryV1GetGetParamsWithTimeout creates a new SalesOrderItemRepositoryV1GetGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSalesOrderItemRepositoryV1GetGetParamsWithTimeout(timeout time.Duration) *SalesOrderItemRepositoryV1GetGetParams {
	var ()
	return &SalesOrderItemRepositoryV1GetGetParams{

		timeout: timeout,
	}
}

// NewSalesOrderItemRepositoryV1GetGetParamsWithContext creates a new SalesOrderItemRepositoryV1GetGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewSalesOrderItemRepositoryV1GetGetParamsWithContext(ctx context.Context) *SalesOrderItemRepositoryV1GetGetParams {
	var ()
	return &SalesOrderItemRepositoryV1GetGetParams{

		Context: ctx,
	}
}

// NewSalesOrderItemRepositoryV1GetGetParamsWithHTTPClient creates a new SalesOrderItemRepositoryV1GetGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSalesOrderItemRepositoryV1GetGetParamsWithHTTPClient(client *http.Client) *SalesOrderItemRepositoryV1GetGetParams {
	var ()
	return &SalesOrderItemRepositoryV1GetGetParams{
		HTTPClient: client,
	}
}

/*SalesOrderItemRepositoryV1GetGetParams contains all the parameters to send to the API endpoint
for the sales order item repository v1 get get operation typically these are written to a http.Request
*/
type SalesOrderItemRepositoryV1GetGetParams struct {

	/*ID
	  The order item ID.

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the sales order item repository v1 get get params
func (o *SalesOrderItemRepositoryV1GetGetParams) WithTimeout(timeout time.Duration) *SalesOrderItemRepositoryV1GetGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the sales order item repository v1 get get params
func (o *SalesOrderItemRepositoryV1GetGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the sales order item repository v1 get get params
func (o *SalesOrderItemRepositoryV1GetGetParams) WithContext(ctx context.Context) *SalesOrderItemRepositoryV1GetGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the sales order item repository v1 get get params
func (o *SalesOrderItemRepositoryV1GetGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the sales order item repository v1 get get params
func (o *SalesOrderItemRepositoryV1GetGetParams) WithHTTPClient(client *http.Client) *SalesOrderItemRepositoryV1GetGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the sales order item repository v1 get get params
func (o *SalesOrderItemRepositoryV1GetGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the sales order item repository v1 get get params
func (o *SalesOrderItemRepositoryV1GetGetParams) WithID(id int64) *SalesOrderItemRepositoryV1GetGetParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the sales order item repository v1 get get params
func (o *SalesOrderItemRepositoryV1GetGetParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *SalesOrderItemRepositoryV1GetGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
