// Code generated by go-swagger; DO NOT EDIT.

package directory_currency_information_acquirer_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new directory currency information acquirer v1 API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for directory currency information acquirer v1 API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
DirectoryCurrencyInformationAcquirerV1GetCurrencyInfoGet Get currency information for the store.
*/
func (a *Client) DirectoryCurrencyInformationAcquirerV1GetCurrencyInfoGet(params *DirectoryCurrencyInformationAcquirerV1GetCurrencyInfoGetParams) (*DirectoryCurrencyInformationAcquirerV1GetCurrencyInfoGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDirectoryCurrencyInformationAcquirerV1GetCurrencyInfoGetParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "directoryCurrencyInformationAcquirerV1GetCurrencyInfoGet",
		Method:             "GET",
		PathPattern:        "/V1/directory/currency",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DirectoryCurrencyInformationAcquirerV1GetCurrencyInfoGetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*DirectoryCurrencyInformationAcquirerV1GetCurrencyInfoGetOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
