// Code generated by go-swagger; DO NOT EDIT.

package quote_cart_item_repository_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	models "flamingo.me/flamingo-commerce-adapter-magento2/magento2/infrastructure/swaggerclient/models"
)

// QuoteCartItemRepositoryV1SavePostMineReader is a Reader for the QuoteCartItemRepositoryV1SavePostMine structure.
type QuoteCartItemRepositoryV1SavePostMineReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *QuoteCartItemRepositoryV1SavePostMineReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewQuoteCartItemRepositoryV1SavePostMineOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewQuoteCartItemRepositoryV1SavePostMineBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewQuoteCartItemRepositoryV1SavePostMineUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewQuoteCartItemRepositoryV1SavePostMineDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewQuoteCartItemRepositoryV1SavePostMineOK creates a QuoteCartItemRepositoryV1SavePostMineOK with default headers values
func NewQuoteCartItemRepositoryV1SavePostMineOK() *QuoteCartItemRepositoryV1SavePostMineOK {
	return &QuoteCartItemRepositoryV1SavePostMineOK{}
}

/*QuoteCartItemRepositoryV1SavePostMineOK handles this case with default header values.

200 Success.
*/
type QuoteCartItemRepositoryV1SavePostMineOK struct {
	Payload *models.QuoteDataCartItemInterface
}

func (o *QuoteCartItemRepositoryV1SavePostMineOK) Error() string {
	return fmt.Sprintf("[POST /V1/carts/mine/items][%d] quoteCartItemRepositoryV1SavePostMineOK  %+v", 200, o.Payload)
}

func (o *QuoteCartItemRepositoryV1SavePostMineOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.QuoteDataCartItemInterface)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewQuoteCartItemRepositoryV1SavePostMineBadRequest creates a QuoteCartItemRepositoryV1SavePostMineBadRequest with default headers values
func NewQuoteCartItemRepositoryV1SavePostMineBadRequest() *QuoteCartItemRepositoryV1SavePostMineBadRequest {
	return &QuoteCartItemRepositoryV1SavePostMineBadRequest{}
}

/*QuoteCartItemRepositoryV1SavePostMineBadRequest handles this case with default header values.

400 Bad Request
*/
type QuoteCartItemRepositoryV1SavePostMineBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *QuoteCartItemRepositoryV1SavePostMineBadRequest) Error() string {
	return fmt.Sprintf("[POST /V1/carts/mine/items][%d] quoteCartItemRepositoryV1SavePostMineBadRequest  %+v", 400, o.Payload)
}

func (o *QuoteCartItemRepositoryV1SavePostMineBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewQuoteCartItemRepositoryV1SavePostMineUnauthorized creates a QuoteCartItemRepositoryV1SavePostMineUnauthorized with default headers values
func NewQuoteCartItemRepositoryV1SavePostMineUnauthorized() *QuoteCartItemRepositoryV1SavePostMineUnauthorized {
	return &QuoteCartItemRepositoryV1SavePostMineUnauthorized{}
}

/*QuoteCartItemRepositoryV1SavePostMineUnauthorized handles this case with default header values.

401 Unauthorized
*/
type QuoteCartItemRepositoryV1SavePostMineUnauthorized struct {
	Payload *models.ErrorResponse
}

func (o *QuoteCartItemRepositoryV1SavePostMineUnauthorized) Error() string {
	return fmt.Sprintf("[POST /V1/carts/mine/items][%d] quoteCartItemRepositoryV1SavePostMineUnauthorized  %+v", 401, o.Payload)
}

func (o *QuoteCartItemRepositoryV1SavePostMineUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewQuoteCartItemRepositoryV1SavePostMineDefault creates a QuoteCartItemRepositoryV1SavePostMineDefault with default headers values
func NewQuoteCartItemRepositoryV1SavePostMineDefault(code int) *QuoteCartItemRepositoryV1SavePostMineDefault {
	return &QuoteCartItemRepositoryV1SavePostMineDefault{
		_statusCode: code,
	}
}

/*QuoteCartItemRepositoryV1SavePostMineDefault handles this case with default header values.

Unexpected error
*/
type QuoteCartItemRepositoryV1SavePostMineDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the quote cart item repository v1 save post mine default response
func (o *QuoteCartItemRepositoryV1SavePostMineDefault) Code() int {
	return o._statusCode
}

func (o *QuoteCartItemRepositoryV1SavePostMineDefault) Error() string {
	return fmt.Sprintf("[POST /V1/carts/mine/items][%d] quoteCartItemRepositoryV1SavePostMine default  %+v", o._statusCode, o.Payload)
}

func (o *QuoteCartItemRepositoryV1SavePostMineDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*QuoteCartItemRepositoryV1SavePostMineBody quote cart item repository v1 save post mine body
swagger:model QuoteCartItemRepositoryV1SavePostMineBody
*/
type QuoteCartItemRepositoryV1SavePostMineBody struct {

	// cart item
	// Required: true
	CartItem *models.QuoteDataCartItemInterface `json:"cartItem"`
}

// Validate validates this quote cart item repository v1 save post mine body
func (o *QuoteCartItemRepositoryV1SavePostMineBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCartItem(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *QuoteCartItemRepositoryV1SavePostMineBody) validateCartItem(formats strfmt.Registry) error {

	if err := validate.Required("quoteCartItemRepositoryV1SavePostBody"+"."+"cartItem", "body", o.CartItem); err != nil {
		return err
	}

	if o.CartItem != nil {
		if err := o.CartItem.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("quoteCartItemRepositoryV1SavePostBody" + "." + "cartItem")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *QuoteCartItemRepositoryV1SavePostMineBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *QuoteCartItemRepositoryV1SavePostMineBody) UnmarshalBinary(b []byte) error {
	var res QuoteCartItemRepositoryV1SavePostMineBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
