// Code generated by go-swagger; DO NOT EDIT.

package tax_tax_rate_repository_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "flamingo.me/flamingo-commerce-adapter-magento2/magento2/infrastructure/swaggerclient/models"
)

// TaxTaxRateRepositoryV1GetGetReader is a Reader for the TaxTaxRateRepositoryV1GetGet structure.
type TaxTaxRateRepositoryV1GetGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TaxTaxRateRepositoryV1GetGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewTaxTaxRateRepositoryV1GetGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewTaxTaxRateRepositoryV1GetGetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewTaxTaxRateRepositoryV1GetGetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewTaxTaxRateRepositoryV1GetGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewTaxTaxRateRepositoryV1GetGetOK creates a TaxTaxRateRepositoryV1GetGetOK with default headers values
func NewTaxTaxRateRepositoryV1GetGetOK() *TaxTaxRateRepositoryV1GetGetOK {
	return &TaxTaxRateRepositoryV1GetGetOK{}
}

/*TaxTaxRateRepositoryV1GetGetOK handles this case with default header values.

200 Success.
*/
type TaxTaxRateRepositoryV1GetGetOK struct {
	Payload *models.TaxDataTaxRateInterface
}

func (o *TaxTaxRateRepositoryV1GetGetOK) Error() string {
	return fmt.Sprintf("[GET /V1/taxRates/{rateId}][%d] taxTaxRateRepositoryV1GetGetOK  %+v", 200, o.Payload)
}

func (o *TaxTaxRateRepositoryV1GetGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TaxDataTaxRateInterface)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTaxTaxRateRepositoryV1GetGetBadRequest creates a TaxTaxRateRepositoryV1GetGetBadRequest with default headers values
func NewTaxTaxRateRepositoryV1GetGetBadRequest() *TaxTaxRateRepositoryV1GetGetBadRequest {
	return &TaxTaxRateRepositoryV1GetGetBadRequest{}
}

/*TaxTaxRateRepositoryV1GetGetBadRequest handles this case with default header values.

400 Bad Request
*/
type TaxTaxRateRepositoryV1GetGetBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *TaxTaxRateRepositoryV1GetGetBadRequest) Error() string {
	return fmt.Sprintf("[GET /V1/taxRates/{rateId}][%d] taxTaxRateRepositoryV1GetGetBadRequest  %+v", 400, o.Payload)
}

func (o *TaxTaxRateRepositoryV1GetGetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTaxTaxRateRepositoryV1GetGetUnauthorized creates a TaxTaxRateRepositoryV1GetGetUnauthorized with default headers values
func NewTaxTaxRateRepositoryV1GetGetUnauthorized() *TaxTaxRateRepositoryV1GetGetUnauthorized {
	return &TaxTaxRateRepositoryV1GetGetUnauthorized{}
}

/*TaxTaxRateRepositoryV1GetGetUnauthorized handles this case with default header values.

401 Unauthorized
*/
type TaxTaxRateRepositoryV1GetGetUnauthorized struct {
	Payload *models.ErrorResponse
}

func (o *TaxTaxRateRepositoryV1GetGetUnauthorized) Error() string {
	return fmt.Sprintf("[GET /V1/taxRates/{rateId}][%d] taxTaxRateRepositoryV1GetGetUnauthorized  %+v", 401, o.Payload)
}

func (o *TaxTaxRateRepositoryV1GetGetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTaxTaxRateRepositoryV1GetGetDefault creates a TaxTaxRateRepositoryV1GetGetDefault with default headers values
func NewTaxTaxRateRepositoryV1GetGetDefault(code int) *TaxTaxRateRepositoryV1GetGetDefault {
	return &TaxTaxRateRepositoryV1GetGetDefault{
		_statusCode: code,
	}
}

/*TaxTaxRateRepositoryV1GetGetDefault handles this case with default header values.

Unexpected error
*/
type TaxTaxRateRepositoryV1GetGetDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the tax tax rate repository v1 get get default response
func (o *TaxTaxRateRepositoryV1GetGetDefault) Code() int {
	return o._statusCode
}

func (o *TaxTaxRateRepositoryV1GetGetDefault) Error() string {
	return fmt.Sprintf("[GET /V1/taxRates/{rateId}][%d] taxTaxRateRepositoryV1GetGet default  %+v", o._statusCode, o.Payload)
}

func (o *TaxTaxRateRepositoryV1GetGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
