// Code generated by go-swagger; DO NOT EDIT.

package quote_guest_shipping_method_management_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewQuoteGuestShippingMethodManagementV1GetListGetParams creates a new QuoteGuestShippingMethodManagementV1GetListGetParams object
// with the default values initialized.
func NewQuoteGuestShippingMethodManagementV1GetListGetParams() *QuoteGuestShippingMethodManagementV1GetListGetParams {
	var ()
	return &QuoteGuestShippingMethodManagementV1GetListGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewQuoteGuestShippingMethodManagementV1GetListGetParamsWithTimeout creates a new QuoteGuestShippingMethodManagementV1GetListGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewQuoteGuestShippingMethodManagementV1GetListGetParamsWithTimeout(timeout time.Duration) *QuoteGuestShippingMethodManagementV1GetListGetParams {
	var ()
	return &QuoteGuestShippingMethodManagementV1GetListGetParams{

		timeout: timeout,
	}
}

// NewQuoteGuestShippingMethodManagementV1GetListGetParamsWithContext creates a new QuoteGuestShippingMethodManagementV1GetListGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewQuoteGuestShippingMethodManagementV1GetListGetParamsWithContext(ctx context.Context) *QuoteGuestShippingMethodManagementV1GetListGetParams {
	var ()
	return &QuoteGuestShippingMethodManagementV1GetListGetParams{

		Context: ctx,
	}
}

// NewQuoteGuestShippingMethodManagementV1GetListGetParamsWithHTTPClient creates a new QuoteGuestShippingMethodManagementV1GetListGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewQuoteGuestShippingMethodManagementV1GetListGetParamsWithHTTPClient(client *http.Client) *QuoteGuestShippingMethodManagementV1GetListGetParams {
	var ()
	return &QuoteGuestShippingMethodManagementV1GetListGetParams{
		HTTPClient: client,
	}
}

/*QuoteGuestShippingMethodManagementV1GetListGetParams contains all the parameters to send to the API endpoint
for the quote guest shipping method management v1 get list get operation typically these are written to a http.Request
*/
type QuoteGuestShippingMethodManagementV1GetListGetParams struct {

	/*CartID
	  The shopping cart ID.

	*/
	CartID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the quote guest shipping method management v1 get list get params
func (o *QuoteGuestShippingMethodManagementV1GetListGetParams) WithTimeout(timeout time.Duration) *QuoteGuestShippingMethodManagementV1GetListGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the quote guest shipping method management v1 get list get params
func (o *QuoteGuestShippingMethodManagementV1GetListGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the quote guest shipping method management v1 get list get params
func (o *QuoteGuestShippingMethodManagementV1GetListGetParams) WithContext(ctx context.Context) *QuoteGuestShippingMethodManagementV1GetListGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the quote guest shipping method management v1 get list get params
func (o *QuoteGuestShippingMethodManagementV1GetListGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the quote guest shipping method management v1 get list get params
func (o *QuoteGuestShippingMethodManagementV1GetListGetParams) WithHTTPClient(client *http.Client) *QuoteGuestShippingMethodManagementV1GetListGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the quote guest shipping method management v1 get list get params
func (o *QuoteGuestShippingMethodManagementV1GetListGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCartID adds the cartID to the quote guest shipping method management v1 get list get params
func (o *QuoteGuestShippingMethodManagementV1GetListGetParams) WithCartID(cartID string) *QuoteGuestShippingMethodManagementV1GetListGetParams {
	o.SetCartID(cartID)
	return o
}

// SetCartID adds the cartId to the quote guest shipping method management v1 get list get params
func (o *QuoteGuestShippingMethodManagementV1GetListGetParams) SetCartID(cartID string) {
	o.CartID = cartID
}

// WriteToRequest writes these params to a swagger request
func (o *QuoteGuestShippingMethodManagementV1GetListGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cartId
	if err := r.SetPathParam("cartId", o.CartID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
