// Code generated by go-swagger; DO NOT EDIT.

package bundle_product_link_management_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	models "flamingo.me/flamingo-commerce-adapter-magento2/magento2/infrastructure/swaggerclient/models"
)

// BundleProductLinkManagementV1SaveChildPutReader is a Reader for the BundleProductLinkManagementV1SaveChildPut structure.
type BundleProductLinkManagementV1SaveChildPutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *BundleProductLinkManagementV1SaveChildPutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewBundleProductLinkManagementV1SaveChildPutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewBundleProductLinkManagementV1SaveChildPutBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewBundleProductLinkManagementV1SaveChildPutUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewBundleProductLinkManagementV1SaveChildPutDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewBundleProductLinkManagementV1SaveChildPutOK creates a BundleProductLinkManagementV1SaveChildPutOK with default headers values
func NewBundleProductLinkManagementV1SaveChildPutOK() *BundleProductLinkManagementV1SaveChildPutOK {
	return &BundleProductLinkManagementV1SaveChildPutOK{}
}

/*BundleProductLinkManagementV1SaveChildPutOK handles this case with default header values.

200 Success.
*/
type BundleProductLinkManagementV1SaveChildPutOK struct {
	Payload bool
}

func (o *BundleProductLinkManagementV1SaveChildPutOK) Error() string {
	return fmt.Sprintf("[PUT /V1/bundle-products/{sku}/links/{id}][%d] bundleProductLinkManagementV1SaveChildPutOK  %+v", 200, o.Payload)
}

func (o *BundleProductLinkManagementV1SaveChildPutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBundleProductLinkManagementV1SaveChildPutBadRequest creates a BundleProductLinkManagementV1SaveChildPutBadRequest with default headers values
func NewBundleProductLinkManagementV1SaveChildPutBadRequest() *BundleProductLinkManagementV1SaveChildPutBadRequest {
	return &BundleProductLinkManagementV1SaveChildPutBadRequest{}
}

/*BundleProductLinkManagementV1SaveChildPutBadRequest handles this case with default header values.

400 Bad Request
*/
type BundleProductLinkManagementV1SaveChildPutBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *BundleProductLinkManagementV1SaveChildPutBadRequest) Error() string {
	return fmt.Sprintf("[PUT /V1/bundle-products/{sku}/links/{id}][%d] bundleProductLinkManagementV1SaveChildPutBadRequest  %+v", 400, o.Payload)
}

func (o *BundleProductLinkManagementV1SaveChildPutBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBundleProductLinkManagementV1SaveChildPutUnauthorized creates a BundleProductLinkManagementV1SaveChildPutUnauthorized with default headers values
func NewBundleProductLinkManagementV1SaveChildPutUnauthorized() *BundleProductLinkManagementV1SaveChildPutUnauthorized {
	return &BundleProductLinkManagementV1SaveChildPutUnauthorized{}
}

/*BundleProductLinkManagementV1SaveChildPutUnauthorized handles this case with default header values.

401 Unauthorized
*/
type BundleProductLinkManagementV1SaveChildPutUnauthorized struct {
	Payload *models.ErrorResponse
}

func (o *BundleProductLinkManagementV1SaveChildPutUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /V1/bundle-products/{sku}/links/{id}][%d] bundleProductLinkManagementV1SaveChildPutUnauthorized  %+v", 401, o.Payload)
}

func (o *BundleProductLinkManagementV1SaveChildPutUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBundleProductLinkManagementV1SaveChildPutDefault creates a BundleProductLinkManagementV1SaveChildPutDefault with default headers values
func NewBundleProductLinkManagementV1SaveChildPutDefault(code int) *BundleProductLinkManagementV1SaveChildPutDefault {
	return &BundleProductLinkManagementV1SaveChildPutDefault{
		_statusCode: code,
	}
}

/*BundleProductLinkManagementV1SaveChildPutDefault handles this case with default header values.

Unexpected error
*/
type BundleProductLinkManagementV1SaveChildPutDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the bundle product link management v1 save child put default response
func (o *BundleProductLinkManagementV1SaveChildPutDefault) Code() int {
	return o._statusCode
}

func (o *BundleProductLinkManagementV1SaveChildPutDefault) Error() string {
	return fmt.Sprintf("[PUT /V1/bundle-products/{sku}/links/{id}][%d] bundleProductLinkManagementV1SaveChildPut default  %+v", o._statusCode, o.Payload)
}

func (o *BundleProductLinkManagementV1SaveChildPutDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*BundleProductLinkManagementV1SaveChildPutBody bundle product link management v1 save child put body
swagger:model BundleProductLinkManagementV1SaveChildPutBody
*/
type BundleProductLinkManagementV1SaveChildPutBody struct {

	// linked product
	// Required: true
	LinkedProduct *models.BundleDataLinkInterface `json:"linkedProduct"`
}

// Validate validates this bundle product link management v1 save child put body
func (o *BundleProductLinkManagementV1SaveChildPutBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateLinkedProduct(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *BundleProductLinkManagementV1SaveChildPutBody) validateLinkedProduct(formats strfmt.Registry) error {

	if err := validate.Required("bundleProductLinkManagementV1SaveChildPutBody"+"."+"linkedProduct", "body", o.LinkedProduct); err != nil {
		return err
	}

	if o.LinkedProduct != nil {
		if err := o.LinkedProduct.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("bundleProductLinkManagementV1SaveChildPutBody" + "." + "linkedProduct")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *BundleProductLinkManagementV1SaveChildPutBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *BundleProductLinkManagementV1SaveChildPutBody) UnmarshalBinary(b []byte) error {
	var res BundleProductLinkManagementV1SaveChildPutBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
