// Code generated by go-swagger; DO NOT EDIT.

package bundle_product_link_management_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "flamingo.me/flamingo-commerce-adapter-magento2/magento2/infrastructure/swaggerclient/models"
)

// BundleProductLinkManagementV1GetChildrenGetReader is a Reader for the BundleProductLinkManagementV1GetChildrenGet structure.
type BundleProductLinkManagementV1GetChildrenGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *BundleProductLinkManagementV1GetChildrenGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewBundleProductLinkManagementV1GetChildrenGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewBundleProductLinkManagementV1GetChildrenGetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewBundleProductLinkManagementV1GetChildrenGetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewBundleProductLinkManagementV1GetChildrenGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewBundleProductLinkManagementV1GetChildrenGetOK creates a BundleProductLinkManagementV1GetChildrenGetOK with default headers values
func NewBundleProductLinkManagementV1GetChildrenGetOK() *BundleProductLinkManagementV1GetChildrenGetOK {
	return &BundleProductLinkManagementV1GetChildrenGetOK{}
}

/*BundleProductLinkManagementV1GetChildrenGetOK handles this case with default header values.

200 Success.
*/
type BundleProductLinkManagementV1GetChildrenGetOK struct {
	Payload []*models.BundleDataLinkInterface
}

func (o *BundleProductLinkManagementV1GetChildrenGetOK) Error() string {
	return fmt.Sprintf("[GET /V1/bundle-products/{productSku}/children][%d] bundleProductLinkManagementV1GetChildrenGetOK  %+v", 200, o.Payload)
}

func (o *BundleProductLinkManagementV1GetChildrenGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBundleProductLinkManagementV1GetChildrenGetBadRequest creates a BundleProductLinkManagementV1GetChildrenGetBadRequest with default headers values
func NewBundleProductLinkManagementV1GetChildrenGetBadRequest() *BundleProductLinkManagementV1GetChildrenGetBadRequest {
	return &BundleProductLinkManagementV1GetChildrenGetBadRequest{}
}

/*BundleProductLinkManagementV1GetChildrenGetBadRequest handles this case with default header values.

400 Bad Request
*/
type BundleProductLinkManagementV1GetChildrenGetBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *BundleProductLinkManagementV1GetChildrenGetBadRequest) Error() string {
	return fmt.Sprintf("[GET /V1/bundle-products/{productSku}/children][%d] bundleProductLinkManagementV1GetChildrenGetBadRequest  %+v", 400, o.Payload)
}

func (o *BundleProductLinkManagementV1GetChildrenGetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBundleProductLinkManagementV1GetChildrenGetUnauthorized creates a BundleProductLinkManagementV1GetChildrenGetUnauthorized with default headers values
func NewBundleProductLinkManagementV1GetChildrenGetUnauthorized() *BundleProductLinkManagementV1GetChildrenGetUnauthorized {
	return &BundleProductLinkManagementV1GetChildrenGetUnauthorized{}
}

/*BundleProductLinkManagementV1GetChildrenGetUnauthorized handles this case with default header values.

401 Unauthorized
*/
type BundleProductLinkManagementV1GetChildrenGetUnauthorized struct {
	Payload *models.ErrorResponse
}

func (o *BundleProductLinkManagementV1GetChildrenGetUnauthorized) Error() string {
	return fmt.Sprintf("[GET /V1/bundle-products/{productSku}/children][%d] bundleProductLinkManagementV1GetChildrenGetUnauthorized  %+v", 401, o.Payload)
}

func (o *BundleProductLinkManagementV1GetChildrenGetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBundleProductLinkManagementV1GetChildrenGetDefault creates a BundleProductLinkManagementV1GetChildrenGetDefault with default headers values
func NewBundleProductLinkManagementV1GetChildrenGetDefault(code int) *BundleProductLinkManagementV1GetChildrenGetDefault {
	return &BundleProductLinkManagementV1GetChildrenGetDefault{
		_statusCode: code,
	}
}

/*BundleProductLinkManagementV1GetChildrenGetDefault handles this case with default header values.

Unexpected error
*/
type BundleProductLinkManagementV1GetChildrenGetDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the bundle product link management v1 get children get default response
func (o *BundleProductLinkManagementV1GetChildrenGetDefault) Code() int {
	return o._statusCode
}

func (o *BundleProductLinkManagementV1GetChildrenGetDefault) Error() string {
	return fmt.Sprintf("[GET /V1/bundle-products/{productSku}/children][%d] bundleProductLinkManagementV1GetChildrenGet default  %+v", o._statusCode, o.Payload)
}

func (o *BundleProductLinkManagementV1GetChildrenGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
