// Code generated by go-swagger; DO NOT EDIT.

package backend_module_service_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewBackendModuleServiceV1GetModulesGetParams creates a new BackendModuleServiceV1GetModulesGetParams object
// with the default values initialized.
func NewBackendModuleServiceV1GetModulesGetParams() *BackendModuleServiceV1GetModulesGetParams {

	return &BackendModuleServiceV1GetModulesGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewBackendModuleServiceV1GetModulesGetParamsWithTimeout creates a new BackendModuleServiceV1GetModulesGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewBackendModuleServiceV1GetModulesGetParamsWithTimeout(timeout time.Duration) *BackendModuleServiceV1GetModulesGetParams {

	return &BackendModuleServiceV1GetModulesGetParams{

		timeout: timeout,
	}
}

// NewBackendModuleServiceV1GetModulesGetParamsWithContext creates a new BackendModuleServiceV1GetModulesGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewBackendModuleServiceV1GetModulesGetParamsWithContext(ctx context.Context) *BackendModuleServiceV1GetModulesGetParams {

	return &BackendModuleServiceV1GetModulesGetParams{

		Context: ctx,
	}
}

// NewBackendModuleServiceV1GetModulesGetParamsWithHTTPClient creates a new BackendModuleServiceV1GetModulesGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewBackendModuleServiceV1GetModulesGetParamsWithHTTPClient(client *http.Client) *BackendModuleServiceV1GetModulesGetParams {

	return &BackendModuleServiceV1GetModulesGetParams{
		HTTPClient: client,
	}
}

/*BackendModuleServiceV1GetModulesGetParams contains all the parameters to send to the API endpoint
for the backend module service v1 get modules get operation typically these are written to a http.Request
*/
type BackendModuleServiceV1GetModulesGetParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the backend module service v1 get modules get params
func (o *BackendModuleServiceV1GetModulesGetParams) WithTimeout(timeout time.Duration) *BackendModuleServiceV1GetModulesGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the backend module service v1 get modules get params
func (o *BackendModuleServiceV1GetModulesGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the backend module service v1 get modules get params
func (o *BackendModuleServiceV1GetModulesGetParams) WithContext(ctx context.Context) *BackendModuleServiceV1GetModulesGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the backend module service v1 get modules get params
func (o *BackendModuleServiceV1GetModulesGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the backend module service v1 get modules get params
func (o *BackendModuleServiceV1GetModulesGetParams) WithHTTPClient(client *http.Client) *BackendModuleServiceV1GetModulesGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the backend module service v1 get modules get params
func (o *BackendModuleServiceV1GetModulesGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *BackendModuleServiceV1GetModulesGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
