// Code generated by go-swagger; DO NOT EDIT.

package quote_cart_management_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "flamingo.me/flamingo-commerce-adapter-magento2/magento2/infrastructure/swaggerclient/models"
)

// QuoteCartManagementV1CreateEmptyCartForCustomerPostMineReader is a Reader for the QuoteCartManagementV1CreateEmptyCartForCustomerPostMine structure.
type QuoteCartManagementV1CreateEmptyCartForCustomerPostMineReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *QuoteCartManagementV1CreateEmptyCartForCustomerPostMineReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewQuoteCartManagementV1CreateEmptyCartForCustomerPostMineOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewQuoteCartManagementV1CreateEmptyCartForCustomerPostMineBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewQuoteCartManagementV1CreateEmptyCartForCustomerPostMineUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewQuoteCartManagementV1CreateEmptyCartForCustomerPostMineDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewQuoteCartManagementV1CreateEmptyCartForCustomerPostMineOK creates a QuoteCartManagementV1CreateEmptyCartForCustomerPostMineOK with default headers values
func NewQuoteCartManagementV1CreateEmptyCartForCustomerPostMineOK() *QuoteCartManagementV1CreateEmptyCartForCustomerPostMineOK {
	return &QuoteCartManagementV1CreateEmptyCartForCustomerPostMineOK{}
}

/*QuoteCartManagementV1CreateEmptyCartForCustomerPostMineOK handles this case with default header values.

200 Success.
*/
type QuoteCartManagementV1CreateEmptyCartForCustomerPostMineOK struct {
	Payload int64
}

func (o *QuoteCartManagementV1CreateEmptyCartForCustomerPostMineOK) Error() string {
	return fmt.Sprintf("[POST /V1/customers/{customerId}/carts][%d] quoteCartManagementV1CreateEmptyCartForCustomerPostMineOK  %+v", 200, o.Payload)
}

func (o *QuoteCartManagementV1CreateEmptyCartForCustomerPostMineOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewQuoteCartManagementV1CreateEmptyCartForCustomerPostMineBadRequest creates a QuoteCartManagementV1CreateEmptyCartForCustomerPostMineBadRequest with default headers values
func NewQuoteCartManagementV1CreateEmptyCartForCustomerPostMineBadRequest() *QuoteCartManagementV1CreateEmptyCartForCustomerPostMineBadRequest {
	return &QuoteCartManagementV1CreateEmptyCartForCustomerPostMineBadRequest{}
}

/*QuoteCartManagementV1CreateEmptyCartForCustomerPostMineBadRequest handles this case with default header values.

400 Bad Request
*/
type QuoteCartManagementV1CreateEmptyCartForCustomerPostMineBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *QuoteCartManagementV1CreateEmptyCartForCustomerPostMineBadRequest) Error() string {
	return fmt.Sprintf("[POST /V1/customers/{customerId}/carts][%d] quoteCartManagementV1CreateEmptyCartForCustomerPostMineBadRequest  %+v", 400, o.Payload)
}

func (o *QuoteCartManagementV1CreateEmptyCartForCustomerPostMineBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewQuoteCartManagementV1CreateEmptyCartForCustomerPostMineUnauthorized creates a QuoteCartManagementV1CreateEmptyCartForCustomerPostMineUnauthorized with default headers values
func NewQuoteCartManagementV1CreateEmptyCartForCustomerPostMineUnauthorized() *QuoteCartManagementV1CreateEmptyCartForCustomerPostMineUnauthorized {
	return &QuoteCartManagementV1CreateEmptyCartForCustomerPostMineUnauthorized{}
}

/*QuoteCartManagementV1CreateEmptyCartForCustomerPostMineUnauthorized handles this case with default header values.

401 Unauthorized
*/
type QuoteCartManagementV1CreateEmptyCartForCustomerPostMineUnauthorized struct {
	Payload *models.ErrorResponse
}

func (o *QuoteCartManagementV1CreateEmptyCartForCustomerPostMineUnauthorized) Error() string {
	return fmt.Sprintf("[POST /V1/customers/{customerId}/carts][%d] quoteCartManagementV1CreateEmptyCartForCustomerPostMineUnauthorized  %+v", 401, o.Payload)
}

func (o *QuoteCartManagementV1CreateEmptyCartForCustomerPostMineUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewQuoteCartManagementV1CreateEmptyCartForCustomerPostMineDefault creates a QuoteCartManagementV1CreateEmptyCartForCustomerPostMineDefault with default headers values
func NewQuoteCartManagementV1CreateEmptyCartForCustomerPostMineDefault(code int) *QuoteCartManagementV1CreateEmptyCartForCustomerPostMineDefault {
	return &QuoteCartManagementV1CreateEmptyCartForCustomerPostMineDefault{
		_statusCode: code,
	}
}

/*QuoteCartManagementV1CreateEmptyCartForCustomerPostMineDefault handles this case with default header values.

Unexpected error
*/
type QuoteCartManagementV1CreateEmptyCartForCustomerPostMineDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the quote cart management v1 create empty cart for customer post mine default response
func (o *QuoteCartManagementV1CreateEmptyCartForCustomerPostMineDefault) Code() int {
	return o._statusCode
}

func (o *QuoteCartManagementV1CreateEmptyCartForCustomerPostMineDefault) Error() string {
	return fmt.Sprintf("[POST /V1/customers/{customerId}/carts][%d] quoteCartManagementV1CreateEmptyCartForCustomerPostMine default  %+v", o._statusCode, o.Payload)
}

func (o *QuoteCartManagementV1CreateEmptyCartForCustomerPostMineDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
