// Code generated by go-swagger; DO NOT EDIT.

package catalog_tier_price_storage_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCatalogTierPriceStorageV1UpdatePostParams creates a new CatalogTierPriceStorageV1UpdatePostParams object
// with the default values initialized.
func NewCatalogTierPriceStorageV1UpdatePostParams() *CatalogTierPriceStorageV1UpdatePostParams {
	var ()
	return &CatalogTierPriceStorageV1UpdatePostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCatalogTierPriceStorageV1UpdatePostParamsWithTimeout creates a new CatalogTierPriceStorageV1UpdatePostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCatalogTierPriceStorageV1UpdatePostParamsWithTimeout(timeout time.Duration) *CatalogTierPriceStorageV1UpdatePostParams {
	var ()
	return &CatalogTierPriceStorageV1UpdatePostParams{

		timeout: timeout,
	}
}

// NewCatalogTierPriceStorageV1UpdatePostParamsWithContext creates a new CatalogTierPriceStorageV1UpdatePostParams object
// with the default values initialized, and the ability to set a context for a request
func NewCatalogTierPriceStorageV1UpdatePostParamsWithContext(ctx context.Context) *CatalogTierPriceStorageV1UpdatePostParams {
	var ()
	return &CatalogTierPriceStorageV1UpdatePostParams{

		Context: ctx,
	}
}

// NewCatalogTierPriceStorageV1UpdatePostParamsWithHTTPClient creates a new CatalogTierPriceStorageV1UpdatePostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCatalogTierPriceStorageV1UpdatePostParamsWithHTTPClient(client *http.Client) *CatalogTierPriceStorageV1UpdatePostParams {
	var ()
	return &CatalogTierPriceStorageV1UpdatePostParams{
		HTTPClient: client,
	}
}

/*CatalogTierPriceStorageV1UpdatePostParams contains all the parameters to send to the API endpoint
for the catalog tier price storage v1 update post operation typically these are written to a http.Request
*/
type CatalogTierPriceStorageV1UpdatePostParams struct {

	/*CatalogTierPriceStorageV1UpdatePostBody*/
	CatalogTierPriceStorageV1UpdatePostBody CatalogTierPriceStorageV1UpdatePostBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the catalog tier price storage v1 update post params
func (o *CatalogTierPriceStorageV1UpdatePostParams) WithTimeout(timeout time.Duration) *CatalogTierPriceStorageV1UpdatePostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the catalog tier price storage v1 update post params
func (o *CatalogTierPriceStorageV1UpdatePostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the catalog tier price storage v1 update post params
func (o *CatalogTierPriceStorageV1UpdatePostParams) WithContext(ctx context.Context) *CatalogTierPriceStorageV1UpdatePostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the catalog tier price storage v1 update post params
func (o *CatalogTierPriceStorageV1UpdatePostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the catalog tier price storage v1 update post params
func (o *CatalogTierPriceStorageV1UpdatePostParams) WithHTTPClient(client *http.Client) *CatalogTierPriceStorageV1UpdatePostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the catalog tier price storage v1 update post params
func (o *CatalogTierPriceStorageV1UpdatePostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCatalogTierPriceStorageV1UpdatePostBody adds the catalogTierPriceStorageV1UpdatePostBody to the catalog tier price storage v1 update post params
func (o *CatalogTierPriceStorageV1UpdatePostParams) WithCatalogTierPriceStorageV1UpdatePostBody(catalogTierPriceStorageV1UpdatePostBody CatalogTierPriceStorageV1UpdatePostBody) *CatalogTierPriceStorageV1UpdatePostParams {
	o.SetCatalogTierPriceStorageV1UpdatePostBody(catalogTierPriceStorageV1UpdatePostBody)
	return o
}

// SetCatalogTierPriceStorageV1UpdatePostBody adds the catalogTierPriceStorageV1UpdatePostBody to the catalog tier price storage v1 update post params
func (o *CatalogTierPriceStorageV1UpdatePostParams) SetCatalogTierPriceStorageV1UpdatePostBody(catalogTierPriceStorageV1UpdatePostBody CatalogTierPriceStorageV1UpdatePostBody) {
	o.CatalogTierPriceStorageV1UpdatePostBody = catalogTierPriceStorageV1UpdatePostBody
}

// WriteToRequest writes these params to a swagger request
func (o *CatalogTierPriceStorageV1UpdatePostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.CatalogTierPriceStorageV1UpdatePostBody); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
