// Code generated by go-swagger; DO NOT EDIT.

package negotiable_quote_payment_information_management_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewNegotiableQuotePaymentInformationManagementV1GetPaymentInformationGetParams creates a new NegotiableQuotePaymentInformationManagementV1GetPaymentInformationGetParams object
// with the default values initialized.
func NewNegotiableQuotePaymentInformationManagementV1GetPaymentInformationGetParams() *NegotiableQuotePaymentInformationManagementV1GetPaymentInformationGetParams {
	var ()
	return &NegotiableQuotePaymentInformationManagementV1GetPaymentInformationGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewNegotiableQuotePaymentInformationManagementV1GetPaymentInformationGetParamsWithTimeout creates a new NegotiableQuotePaymentInformationManagementV1GetPaymentInformationGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewNegotiableQuotePaymentInformationManagementV1GetPaymentInformationGetParamsWithTimeout(timeout time.Duration) *NegotiableQuotePaymentInformationManagementV1GetPaymentInformationGetParams {
	var ()
	return &NegotiableQuotePaymentInformationManagementV1GetPaymentInformationGetParams{

		timeout: timeout,
	}
}

// NewNegotiableQuotePaymentInformationManagementV1GetPaymentInformationGetParamsWithContext creates a new NegotiableQuotePaymentInformationManagementV1GetPaymentInformationGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewNegotiableQuotePaymentInformationManagementV1GetPaymentInformationGetParamsWithContext(ctx context.Context) *NegotiableQuotePaymentInformationManagementV1GetPaymentInformationGetParams {
	var ()
	return &NegotiableQuotePaymentInformationManagementV1GetPaymentInformationGetParams{

		Context: ctx,
	}
}

// NewNegotiableQuotePaymentInformationManagementV1GetPaymentInformationGetParamsWithHTTPClient creates a new NegotiableQuotePaymentInformationManagementV1GetPaymentInformationGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewNegotiableQuotePaymentInformationManagementV1GetPaymentInformationGetParamsWithHTTPClient(client *http.Client) *NegotiableQuotePaymentInformationManagementV1GetPaymentInformationGetParams {
	var ()
	return &NegotiableQuotePaymentInformationManagementV1GetPaymentInformationGetParams{
		HTTPClient: client,
	}
}

/*NegotiableQuotePaymentInformationManagementV1GetPaymentInformationGetParams contains all the parameters to send to the API endpoint
for the negotiable quote payment information management v1 get payment information get operation typically these are written to a http.Request
*/
type NegotiableQuotePaymentInformationManagementV1GetPaymentInformationGetParams struct {

	/*CartID*/
	CartID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the negotiable quote payment information management v1 get payment information get params
func (o *NegotiableQuotePaymentInformationManagementV1GetPaymentInformationGetParams) WithTimeout(timeout time.Duration) *NegotiableQuotePaymentInformationManagementV1GetPaymentInformationGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the negotiable quote payment information management v1 get payment information get params
func (o *NegotiableQuotePaymentInformationManagementV1GetPaymentInformationGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the negotiable quote payment information management v1 get payment information get params
func (o *NegotiableQuotePaymentInformationManagementV1GetPaymentInformationGetParams) WithContext(ctx context.Context) *NegotiableQuotePaymentInformationManagementV1GetPaymentInformationGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the negotiable quote payment information management v1 get payment information get params
func (o *NegotiableQuotePaymentInformationManagementV1GetPaymentInformationGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the negotiable quote payment information management v1 get payment information get params
func (o *NegotiableQuotePaymentInformationManagementV1GetPaymentInformationGetParams) WithHTTPClient(client *http.Client) *NegotiableQuotePaymentInformationManagementV1GetPaymentInformationGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the negotiable quote payment information management v1 get payment information get params
func (o *NegotiableQuotePaymentInformationManagementV1GetPaymentInformationGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCartID adds the cartID to the negotiable quote payment information management v1 get payment information get params
func (o *NegotiableQuotePaymentInformationManagementV1GetPaymentInformationGetParams) WithCartID(cartID int64) *NegotiableQuotePaymentInformationManagementV1GetPaymentInformationGetParams {
	o.SetCartID(cartID)
	return o
}

// SetCartID adds the cartId to the negotiable quote payment information management v1 get payment information get params
func (o *NegotiableQuotePaymentInformationManagementV1GetPaymentInformationGetParams) SetCartID(cartID int64) {
	o.CartID = cartID
}

// WriteToRequest writes these params to a swagger request
func (o *NegotiableQuotePaymentInformationManagementV1GetPaymentInformationGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cartId
	if err := r.SetPathParam("cartId", swag.FormatInt64(o.CartID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
