// Code generated by go-swagger; DO NOT EDIT.

package negotiable_quote_payment_information_management_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewNegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParams creates a new NegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParams object
// with the default values initialized.
func NewNegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParams() *NegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParams {
	var ()
	return &NegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewNegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParamsWithTimeout creates a new NegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewNegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParamsWithTimeout(timeout time.Duration) *NegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParams {
	var ()
	return &NegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParams{

		timeout: timeout,
	}
}

// NewNegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParamsWithContext creates a new NegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParams object
// with the default values initialized, and the ability to set a context for a request
func NewNegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParamsWithContext(ctx context.Context) *NegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParams {
	var ()
	return &NegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParams{

		Context: ctx,
	}
}

// NewNegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParamsWithHTTPClient creates a new NegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewNegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParamsWithHTTPClient(client *http.Client) *NegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParams {
	var ()
	return &NegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParams{
		HTTPClient: client,
	}
}

/*NegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParams contains all the parameters to send to the API endpoint
for the negotiable quote payment information management v1 save payment information post operation typically these are written to a http.Request
*/
type NegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParams struct {

	/*CartID*/
	CartID int64
	/*NegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostBody*/
	NegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostBody NegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the negotiable quote payment information management v1 save payment information post params
func (o *NegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParams) WithTimeout(timeout time.Duration) *NegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the negotiable quote payment information management v1 save payment information post params
func (o *NegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the negotiable quote payment information management v1 save payment information post params
func (o *NegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParams) WithContext(ctx context.Context) *NegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the negotiable quote payment information management v1 save payment information post params
func (o *NegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the negotiable quote payment information management v1 save payment information post params
func (o *NegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParams) WithHTTPClient(client *http.Client) *NegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the negotiable quote payment information management v1 save payment information post params
func (o *NegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCartID adds the cartID to the negotiable quote payment information management v1 save payment information post params
func (o *NegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParams) WithCartID(cartID int64) *NegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParams {
	o.SetCartID(cartID)
	return o
}

// SetCartID adds the cartId to the negotiable quote payment information management v1 save payment information post params
func (o *NegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParams) SetCartID(cartID int64) {
	o.CartID = cartID
}

// WithNegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostBody adds the negotiableQuotePaymentInformationManagementV1SavePaymentInformationPostBody to the negotiable quote payment information management v1 save payment information post params
func (o *NegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParams) WithNegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostBody(negotiableQuotePaymentInformationManagementV1SavePaymentInformationPostBody NegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostBody) *NegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParams {
	o.SetNegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostBody(negotiableQuotePaymentInformationManagementV1SavePaymentInformationPostBody)
	return o
}

// SetNegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostBody adds the negotiableQuotePaymentInformationManagementV1SavePaymentInformationPostBody to the negotiable quote payment information management v1 save payment information post params
func (o *NegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParams) SetNegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostBody(negotiableQuotePaymentInformationManagementV1SavePaymentInformationPostBody NegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostBody) {
	o.NegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostBody = negotiableQuotePaymentInformationManagementV1SavePaymentInformationPostBody
}

// WriteToRequest writes these params to a swagger request
func (o *NegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cartId
	if err := r.SetPathParam("cartId", swag.FormatInt64(o.CartID)); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.NegotiableQuotePaymentInformationManagementV1SavePaymentInformationPostBody); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
