// Code generated by go-swagger; DO NOT EDIT.

package downloadable_link_repository_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDownloadableLinkRepositoryV1SavePutParams creates a new DownloadableLinkRepositoryV1SavePutParams object
// with the default values initialized.
func NewDownloadableLinkRepositoryV1SavePutParams() *DownloadableLinkRepositoryV1SavePutParams {
	var ()
	return &DownloadableLinkRepositoryV1SavePutParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDownloadableLinkRepositoryV1SavePutParamsWithTimeout creates a new DownloadableLinkRepositoryV1SavePutParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDownloadableLinkRepositoryV1SavePutParamsWithTimeout(timeout time.Duration) *DownloadableLinkRepositoryV1SavePutParams {
	var ()
	return &DownloadableLinkRepositoryV1SavePutParams{

		timeout: timeout,
	}
}

// NewDownloadableLinkRepositoryV1SavePutParamsWithContext creates a new DownloadableLinkRepositoryV1SavePutParams object
// with the default values initialized, and the ability to set a context for a request
func NewDownloadableLinkRepositoryV1SavePutParamsWithContext(ctx context.Context) *DownloadableLinkRepositoryV1SavePutParams {
	var ()
	return &DownloadableLinkRepositoryV1SavePutParams{

		Context: ctx,
	}
}

// NewDownloadableLinkRepositoryV1SavePutParamsWithHTTPClient creates a new DownloadableLinkRepositoryV1SavePutParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDownloadableLinkRepositoryV1SavePutParamsWithHTTPClient(client *http.Client) *DownloadableLinkRepositoryV1SavePutParams {
	var ()
	return &DownloadableLinkRepositoryV1SavePutParams{
		HTTPClient: client,
	}
}

/*DownloadableLinkRepositoryV1SavePutParams contains all the parameters to send to the API endpoint
for the downloadable link repository v1 save put operation typically these are written to a http.Request
*/
type DownloadableLinkRepositoryV1SavePutParams struct {

	/*DownloadableLinkRepositoryV1SavePutBody*/
	DownloadableLinkRepositoryV1SavePutBody DownloadableLinkRepositoryV1SavePutBody
	/*ID*/
	ID string
	/*Sku*/
	Sku string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the downloadable link repository v1 save put params
func (o *DownloadableLinkRepositoryV1SavePutParams) WithTimeout(timeout time.Duration) *DownloadableLinkRepositoryV1SavePutParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the downloadable link repository v1 save put params
func (o *DownloadableLinkRepositoryV1SavePutParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the downloadable link repository v1 save put params
func (o *DownloadableLinkRepositoryV1SavePutParams) WithContext(ctx context.Context) *DownloadableLinkRepositoryV1SavePutParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the downloadable link repository v1 save put params
func (o *DownloadableLinkRepositoryV1SavePutParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the downloadable link repository v1 save put params
func (o *DownloadableLinkRepositoryV1SavePutParams) WithHTTPClient(client *http.Client) *DownloadableLinkRepositoryV1SavePutParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the downloadable link repository v1 save put params
func (o *DownloadableLinkRepositoryV1SavePutParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDownloadableLinkRepositoryV1SavePutBody adds the downloadableLinkRepositoryV1SavePutBody to the downloadable link repository v1 save put params
func (o *DownloadableLinkRepositoryV1SavePutParams) WithDownloadableLinkRepositoryV1SavePutBody(downloadableLinkRepositoryV1SavePutBody DownloadableLinkRepositoryV1SavePutBody) *DownloadableLinkRepositoryV1SavePutParams {
	o.SetDownloadableLinkRepositoryV1SavePutBody(downloadableLinkRepositoryV1SavePutBody)
	return o
}

// SetDownloadableLinkRepositoryV1SavePutBody adds the downloadableLinkRepositoryV1SavePutBody to the downloadable link repository v1 save put params
func (o *DownloadableLinkRepositoryV1SavePutParams) SetDownloadableLinkRepositoryV1SavePutBody(downloadableLinkRepositoryV1SavePutBody DownloadableLinkRepositoryV1SavePutBody) {
	o.DownloadableLinkRepositoryV1SavePutBody = downloadableLinkRepositoryV1SavePutBody
}

// WithID adds the id to the downloadable link repository v1 save put params
func (o *DownloadableLinkRepositoryV1SavePutParams) WithID(id string) *DownloadableLinkRepositoryV1SavePutParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the downloadable link repository v1 save put params
func (o *DownloadableLinkRepositoryV1SavePutParams) SetID(id string) {
	o.ID = id
}

// WithSku adds the sku to the downloadable link repository v1 save put params
func (o *DownloadableLinkRepositoryV1SavePutParams) WithSku(sku string) *DownloadableLinkRepositoryV1SavePutParams {
	o.SetSku(sku)
	return o
}

// SetSku adds the sku to the downloadable link repository v1 save put params
func (o *DownloadableLinkRepositoryV1SavePutParams) SetSku(sku string) {
	o.Sku = sku
}

// WriteToRequest writes these params to a swagger request
func (o *DownloadableLinkRepositoryV1SavePutParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.DownloadableLinkRepositoryV1SavePutBody); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param sku
	if err := r.SetPathParam("sku", o.Sku); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
