// Code generated by go-swagger; DO NOT EDIT.

package shared_catalog_shared_catalog_repository_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSharedCatalogSharedCatalogRepositoryV1SavePutParams creates a new SharedCatalogSharedCatalogRepositoryV1SavePutParams object
// with the default values initialized.
func NewSharedCatalogSharedCatalogRepositoryV1SavePutParams() *SharedCatalogSharedCatalogRepositoryV1SavePutParams {
	var ()
	return &SharedCatalogSharedCatalogRepositoryV1SavePutParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSharedCatalogSharedCatalogRepositoryV1SavePutParamsWithTimeout creates a new SharedCatalogSharedCatalogRepositoryV1SavePutParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSharedCatalogSharedCatalogRepositoryV1SavePutParamsWithTimeout(timeout time.Duration) *SharedCatalogSharedCatalogRepositoryV1SavePutParams {
	var ()
	return &SharedCatalogSharedCatalogRepositoryV1SavePutParams{

		timeout: timeout,
	}
}

// NewSharedCatalogSharedCatalogRepositoryV1SavePutParamsWithContext creates a new SharedCatalogSharedCatalogRepositoryV1SavePutParams object
// with the default values initialized, and the ability to set a context for a request
func NewSharedCatalogSharedCatalogRepositoryV1SavePutParamsWithContext(ctx context.Context) *SharedCatalogSharedCatalogRepositoryV1SavePutParams {
	var ()
	return &SharedCatalogSharedCatalogRepositoryV1SavePutParams{

		Context: ctx,
	}
}

// NewSharedCatalogSharedCatalogRepositoryV1SavePutParamsWithHTTPClient creates a new SharedCatalogSharedCatalogRepositoryV1SavePutParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSharedCatalogSharedCatalogRepositoryV1SavePutParamsWithHTTPClient(client *http.Client) *SharedCatalogSharedCatalogRepositoryV1SavePutParams {
	var ()
	return &SharedCatalogSharedCatalogRepositoryV1SavePutParams{
		HTTPClient: client,
	}
}

/*SharedCatalogSharedCatalogRepositoryV1SavePutParams contains all the parameters to send to the API endpoint
for the shared catalog shared catalog repository v1 save put operation typically these are written to a http.Request
*/
type SharedCatalogSharedCatalogRepositoryV1SavePutParams struct {

	/*ID*/
	ID string
	/*SharedCatalogSharedCatalogRepositoryV1SavePutBody*/
	SharedCatalogSharedCatalogRepositoryV1SavePutBody SharedCatalogSharedCatalogRepositoryV1SavePutBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the shared catalog shared catalog repository v1 save put params
func (o *SharedCatalogSharedCatalogRepositoryV1SavePutParams) WithTimeout(timeout time.Duration) *SharedCatalogSharedCatalogRepositoryV1SavePutParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the shared catalog shared catalog repository v1 save put params
func (o *SharedCatalogSharedCatalogRepositoryV1SavePutParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the shared catalog shared catalog repository v1 save put params
func (o *SharedCatalogSharedCatalogRepositoryV1SavePutParams) WithContext(ctx context.Context) *SharedCatalogSharedCatalogRepositoryV1SavePutParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the shared catalog shared catalog repository v1 save put params
func (o *SharedCatalogSharedCatalogRepositoryV1SavePutParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the shared catalog shared catalog repository v1 save put params
func (o *SharedCatalogSharedCatalogRepositoryV1SavePutParams) WithHTTPClient(client *http.Client) *SharedCatalogSharedCatalogRepositoryV1SavePutParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the shared catalog shared catalog repository v1 save put params
func (o *SharedCatalogSharedCatalogRepositoryV1SavePutParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the shared catalog shared catalog repository v1 save put params
func (o *SharedCatalogSharedCatalogRepositoryV1SavePutParams) WithID(id string) *SharedCatalogSharedCatalogRepositoryV1SavePutParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the shared catalog shared catalog repository v1 save put params
func (o *SharedCatalogSharedCatalogRepositoryV1SavePutParams) SetID(id string) {
	o.ID = id
}

// WithSharedCatalogSharedCatalogRepositoryV1SavePutBody adds the sharedCatalogSharedCatalogRepositoryV1SavePutBody to the shared catalog shared catalog repository v1 save put params
func (o *SharedCatalogSharedCatalogRepositoryV1SavePutParams) WithSharedCatalogSharedCatalogRepositoryV1SavePutBody(sharedCatalogSharedCatalogRepositoryV1SavePutBody SharedCatalogSharedCatalogRepositoryV1SavePutBody) *SharedCatalogSharedCatalogRepositoryV1SavePutParams {
	o.SetSharedCatalogSharedCatalogRepositoryV1SavePutBody(sharedCatalogSharedCatalogRepositoryV1SavePutBody)
	return o
}

// SetSharedCatalogSharedCatalogRepositoryV1SavePutBody adds the sharedCatalogSharedCatalogRepositoryV1SavePutBody to the shared catalog shared catalog repository v1 save put params
func (o *SharedCatalogSharedCatalogRepositoryV1SavePutParams) SetSharedCatalogSharedCatalogRepositoryV1SavePutBody(sharedCatalogSharedCatalogRepositoryV1SavePutBody SharedCatalogSharedCatalogRepositoryV1SavePutBody) {
	o.SharedCatalogSharedCatalogRepositoryV1SavePutBody = sharedCatalogSharedCatalogRepositoryV1SavePutBody
}

// WriteToRequest writes these params to a swagger request
func (o *SharedCatalogSharedCatalogRepositoryV1SavePutParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.SharedCatalogSharedCatalogRepositoryV1SavePutBody); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
