// Code generated by go-swagger; DO NOT EDIT.

package company_company_hierarchy_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "flamingo.me/flamingo-commerce-adapter-magento2/magento2/infrastructure/swaggerclient/models"
)

// CompanyCompanyHierarchyV1GetCompanyHierarchyGetReader is a Reader for the CompanyCompanyHierarchyV1GetCompanyHierarchyGet structure.
type CompanyCompanyHierarchyV1GetCompanyHierarchyGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CompanyCompanyHierarchyV1GetCompanyHierarchyGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCompanyCompanyHierarchyV1GetCompanyHierarchyGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewCompanyCompanyHierarchyV1GetCompanyHierarchyGetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewCompanyCompanyHierarchyV1GetCompanyHierarchyGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCompanyCompanyHierarchyV1GetCompanyHierarchyGetOK creates a CompanyCompanyHierarchyV1GetCompanyHierarchyGetOK with default headers values
func NewCompanyCompanyHierarchyV1GetCompanyHierarchyGetOK() *CompanyCompanyHierarchyV1GetCompanyHierarchyGetOK {
	return &CompanyCompanyHierarchyV1GetCompanyHierarchyGetOK{}
}

/*CompanyCompanyHierarchyV1GetCompanyHierarchyGetOK handles this case with default header values.

200 Success.
*/
type CompanyCompanyHierarchyV1GetCompanyHierarchyGetOK struct {
	Payload []*models.CompanyDataHierarchyInterface
}

func (o *CompanyCompanyHierarchyV1GetCompanyHierarchyGetOK) Error() string {
	return fmt.Sprintf("[GET /V1/hierarchy/{id}][%d] companyCompanyHierarchyV1GetCompanyHierarchyGetOK  %+v", 200, o.Payload)
}

func (o *CompanyCompanyHierarchyV1GetCompanyHierarchyGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCompanyCompanyHierarchyV1GetCompanyHierarchyGetUnauthorized creates a CompanyCompanyHierarchyV1GetCompanyHierarchyGetUnauthorized with default headers values
func NewCompanyCompanyHierarchyV1GetCompanyHierarchyGetUnauthorized() *CompanyCompanyHierarchyV1GetCompanyHierarchyGetUnauthorized {
	return &CompanyCompanyHierarchyV1GetCompanyHierarchyGetUnauthorized{}
}

/*CompanyCompanyHierarchyV1GetCompanyHierarchyGetUnauthorized handles this case with default header values.

401 Unauthorized
*/
type CompanyCompanyHierarchyV1GetCompanyHierarchyGetUnauthorized struct {
	Payload *models.ErrorResponse
}

func (o *CompanyCompanyHierarchyV1GetCompanyHierarchyGetUnauthorized) Error() string {
	return fmt.Sprintf("[GET /V1/hierarchy/{id}][%d] companyCompanyHierarchyV1GetCompanyHierarchyGetUnauthorized  %+v", 401, o.Payload)
}

func (o *CompanyCompanyHierarchyV1GetCompanyHierarchyGetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCompanyCompanyHierarchyV1GetCompanyHierarchyGetDefault creates a CompanyCompanyHierarchyV1GetCompanyHierarchyGetDefault with default headers values
func NewCompanyCompanyHierarchyV1GetCompanyHierarchyGetDefault(code int) *CompanyCompanyHierarchyV1GetCompanyHierarchyGetDefault {
	return &CompanyCompanyHierarchyV1GetCompanyHierarchyGetDefault{
		_statusCode: code,
	}
}

/*CompanyCompanyHierarchyV1GetCompanyHierarchyGetDefault handles this case with default header values.

Unexpected error
*/
type CompanyCompanyHierarchyV1GetCompanyHierarchyGetDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the company company hierarchy v1 get company hierarchy get default response
func (o *CompanyCompanyHierarchyV1GetCompanyHierarchyGetDefault) Code() int {
	return o._statusCode
}

func (o *CompanyCompanyHierarchyV1GetCompanyHierarchyGetDefault) Error() string {
	return fmt.Sprintf("[GET /V1/hierarchy/{id}][%d] companyCompanyHierarchyV1GetCompanyHierarchyGet default  %+v", o._statusCode, o.Payload)
}

func (o *CompanyCompanyHierarchyV1GetCompanyHierarchyGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
