// Code generated by go-swagger; DO NOT EDIT.

package company_company_hierarchy_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	models "flamingo.me/flamingo-commerce-adapter-magento2/magento2/infrastructure/swaggerclient/models"
)

// CompanyCompanyHierarchyV1MoveNodePutReader is a Reader for the CompanyCompanyHierarchyV1MoveNodePut structure.
type CompanyCompanyHierarchyV1MoveNodePutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CompanyCompanyHierarchyV1MoveNodePutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 401:
		result := NewCompanyCompanyHierarchyV1MoveNodePutUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewCompanyCompanyHierarchyV1MoveNodePutDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCompanyCompanyHierarchyV1MoveNodePutUnauthorized creates a CompanyCompanyHierarchyV1MoveNodePutUnauthorized with default headers values
func NewCompanyCompanyHierarchyV1MoveNodePutUnauthorized() *CompanyCompanyHierarchyV1MoveNodePutUnauthorized {
	return &CompanyCompanyHierarchyV1MoveNodePutUnauthorized{}
}

/*CompanyCompanyHierarchyV1MoveNodePutUnauthorized handles this case with default header values.

401 Unauthorized
*/
type CompanyCompanyHierarchyV1MoveNodePutUnauthorized struct {
	Payload *models.ErrorResponse
}

func (o *CompanyCompanyHierarchyV1MoveNodePutUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /V1/hierarchy/move/{id}][%d] companyCompanyHierarchyV1MoveNodePutUnauthorized  %+v", 401, o.Payload)
}

func (o *CompanyCompanyHierarchyV1MoveNodePutUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCompanyCompanyHierarchyV1MoveNodePutDefault creates a CompanyCompanyHierarchyV1MoveNodePutDefault with default headers values
func NewCompanyCompanyHierarchyV1MoveNodePutDefault(code int) *CompanyCompanyHierarchyV1MoveNodePutDefault {
	return &CompanyCompanyHierarchyV1MoveNodePutDefault{
		_statusCode: code,
	}
}

/*CompanyCompanyHierarchyV1MoveNodePutDefault handles this case with default header values.

Unexpected error
*/
type CompanyCompanyHierarchyV1MoveNodePutDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the company company hierarchy v1 move node put default response
func (o *CompanyCompanyHierarchyV1MoveNodePutDefault) Code() int {
	return o._statusCode
}

func (o *CompanyCompanyHierarchyV1MoveNodePutDefault) Error() string {
	return fmt.Sprintf("[PUT /V1/hierarchy/move/{id}][%d] companyCompanyHierarchyV1MoveNodePut default  %+v", o._statusCode, o.Payload)
}

func (o *CompanyCompanyHierarchyV1MoveNodePutDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*CompanyCompanyHierarchyV1MoveNodePutBody company company hierarchy v1 move node put body
swagger:model CompanyCompanyHierarchyV1MoveNodePutBody
*/
type CompanyCompanyHierarchyV1MoveNodePutBody struct {

	// new parent Id
	// Required: true
	NewParentID *int64 `json:"newParentId"`
}

// Validate validates this company company hierarchy v1 move node put body
func (o *CompanyCompanyHierarchyV1MoveNodePutBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateNewParentID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CompanyCompanyHierarchyV1MoveNodePutBody) validateNewParentID(formats strfmt.Registry) error {

	if err := validate.Required("companyCompanyHierarchyV1MoveNodePutBody"+"."+"newParentId", "body", o.NewParentID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *CompanyCompanyHierarchyV1MoveNodePutBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CompanyCompanyHierarchyV1MoveNodePutBody) UnmarshalBinary(b []byte) error {
	var res CompanyCompanyHierarchyV1MoveNodePutBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
