// Code generated by go-swagger; DO NOT EDIT.

package configurable_product_configurable_product_management_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	models "flamingo.me/flamingo-commerce-adapter-magento2/magento2/infrastructure/swaggerclient/models"
)

// ConfigurableProductConfigurableProductManagementV1GenerateVariationPutReader is a Reader for the ConfigurableProductConfigurableProductManagementV1GenerateVariationPut structure.
type ConfigurableProductConfigurableProductManagementV1GenerateVariationPutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ConfigurableProductConfigurableProductManagementV1GenerateVariationPutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewConfigurableProductConfigurableProductManagementV1GenerateVariationPutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewConfigurableProductConfigurableProductManagementV1GenerateVariationPutUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewConfigurableProductConfigurableProductManagementV1GenerateVariationPutDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewConfigurableProductConfigurableProductManagementV1GenerateVariationPutOK creates a ConfigurableProductConfigurableProductManagementV1GenerateVariationPutOK with default headers values
func NewConfigurableProductConfigurableProductManagementV1GenerateVariationPutOK() *ConfigurableProductConfigurableProductManagementV1GenerateVariationPutOK {
	return &ConfigurableProductConfigurableProductManagementV1GenerateVariationPutOK{}
}

/*ConfigurableProductConfigurableProductManagementV1GenerateVariationPutOK handles this case with default header values.

200 Success.
*/
type ConfigurableProductConfigurableProductManagementV1GenerateVariationPutOK struct {
	Payload []*models.CatalogDataProductInterface
}

func (o *ConfigurableProductConfigurableProductManagementV1GenerateVariationPutOK) Error() string {
	return fmt.Sprintf("[PUT /V1/configurable-products/variation][%d] configurableProductConfigurableProductManagementV1GenerateVariationPutOK  %+v", 200, o.Payload)
}

func (o *ConfigurableProductConfigurableProductManagementV1GenerateVariationPutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewConfigurableProductConfigurableProductManagementV1GenerateVariationPutUnauthorized creates a ConfigurableProductConfigurableProductManagementV1GenerateVariationPutUnauthorized with default headers values
func NewConfigurableProductConfigurableProductManagementV1GenerateVariationPutUnauthorized() *ConfigurableProductConfigurableProductManagementV1GenerateVariationPutUnauthorized {
	return &ConfigurableProductConfigurableProductManagementV1GenerateVariationPutUnauthorized{}
}

/*ConfigurableProductConfigurableProductManagementV1GenerateVariationPutUnauthorized handles this case with default header values.

401 Unauthorized
*/
type ConfigurableProductConfigurableProductManagementV1GenerateVariationPutUnauthorized struct {
	Payload *models.ErrorResponse
}

func (o *ConfigurableProductConfigurableProductManagementV1GenerateVariationPutUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /V1/configurable-products/variation][%d] configurableProductConfigurableProductManagementV1GenerateVariationPutUnauthorized  %+v", 401, o.Payload)
}

func (o *ConfigurableProductConfigurableProductManagementV1GenerateVariationPutUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewConfigurableProductConfigurableProductManagementV1GenerateVariationPutDefault creates a ConfigurableProductConfigurableProductManagementV1GenerateVariationPutDefault with default headers values
func NewConfigurableProductConfigurableProductManagementV1GenerateVariationPutDefault(code int) *ConfigurableProductConfigurableProductManagementV1GenerateVariationPutDefault {
	return &ConfigurableProductConfigurableProductManagementV1GenerateVariationPutDefault{
		_statusCode: code,
	}
}

/*ConfigurableProductConfigurableProductManagementV1GenerateVariationPutDefault handles this case with default header values.

Unexpected error
*/
type ConfigurableProductConfigurableProductManagementV1GenerateVariationPutDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the configurable product configurable product management v1 generate variation put default response
func (o *ConfigurableProductConfigurableProductManagementV1GenerateVariationPutDefault) Code() int {
	return o._statusCode
}

func (o *ConfigurableProductConfigurableProductManagementV1GenerateVariationPutDefault) Error() string {
	return fmt.Sprintf("[PUT /V1/configurable-products/variation][%d] configurableProductConfigurableProductManagementV1GenerateVariationPut default  %+v", o._statusCode, o.Payload)
}

func (o *ConfigurableProductConfigurableProductManagementV1GenerateVariationPutDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*ConfigurableProductConfigurableProductManagementV1GenerateVariationPutBody configurable product configurable product management v1 generate variation put body
swagger:model ConfigurableProductConfigurableProductManagementV1GenerateVariationPutBody
*/
type ConfigurableProductConfigurableProductManagementV1GenerateVariationPutBody struct {

	// options
	// Required: true
	Options []*models.ConfigurableProductDataOptionInterface `json:"options"`

	// product
	// Required: true
	Product *models.CatalogDataProductInterface `json:"product"`
}

// Validate validates this configurable product configurable product management v1 generate variation put body
func (o *ConfigurableProductConfigurableProductManagementV1GenerateVariationPutBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateOptions(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateProduct(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ConfigurableProductConfigurableProductManagementV1GenerateVariationPutBody) validateOptions(formats strfmt.Registry) error {

	if err := validate.Required("configurableProductConfigurableProductManagementV1GenerateVariationPutBody"+"."+"options", "body", o.Options); err != nil {
		return err
	}

	for i := 0; i < len(o.Options); i++ {
		if swag.IsZero(o.Options[i]) { // not required
			continue
		}

		if o.Options[i] != nil {
			if err := o.Options[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("configurableProductConfigurableProductManagementV1GenerateVariationPutBody" + "." + "options" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *ConfigurableProductConfigurableProductManagementV1GenerateVariationPutBody) validateProduct(formats strfmt.Registry) error {

	if err := validate.Required("configurableProductConfigurableProductManagementV1GenerateVariationPutBody"+"."+"product", "body", o.Product); err != nil {
		return err
	}

	if o.Product != nil {
		if err := o.Product.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("configurableProductConfigurableProductManagementV1GenerateVariationPutBody" + "." + "product")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *ConfigurableProductConfigurableProductManagementV1GenerateVariationPutBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ConfigurableProductConfigurableProductManagementV1GenerateVariationPutBody) UnmarshalBinary(b []byte) error {
	var res ConfigurableProductConfigurableProductManagementV1GenerateVariationPutBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
