// Code generated by go-swagger; DO NOT EDIT.

package quote_cart_total_management_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewQuoteCartTotalManagementV1CollectTotalsPutMineParams creates a new QuoteCartTotalManagementV1CollectTotalsPutMineParams object
// with the default values initialized.
func NewQuoteCartTotalManagementV1CollectTotalsPutMineParams() *QuoteCartTotalManagementV1CollectTotalsPutMineParams {
	var ()
	return &QuoteCartTotalManagementV1CollectTotalsPutMineParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewQuoteCartTotalManagementV1CollectTotalsPutMineParamsWithTimeout creates a new QuoteCartTotalManagementV1CollectTotalsPutMineParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewQuoteCartTotalManagementV1CollectTotalsPutMineParamsWithTimeout(timeout time.Duration) *QuoteCartTotalManagementV1CollectTotalsPutMineParams {
	var ()
	return &QuoteCartTotalManagementV1CollectTotalsPutMineParams{

		timeout: timeout,
	}
}

// NewQuoteCartTotalManagementV1CollectTotalsPutMineParamsWithContext creates a new QuoteCartTotalManagementV1CollectTotalsPutMineParams object
// with the default values initialized, and the ability to set a context for a request
func NewQuoteCartTotalManagementV1CollectTotalsPutMineParamsWithContext(ctx context.Context) *QuoteCartTotalManagementV1CollectTotalsPutMineParams {
	var ()
	return &QuoteCartTotalManagementV1CollectTotalsPutMineParams{

		Context: ctx,
	}
}

// NewQuoteCartTotalManagementV1CollectTotalsPutMineParamsWithHTTPClient creates a new QuoteCartTotalManagementV1CollectTotalsPutMineParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewQuoteCartTotalManagementV1CollectTotalsPutMineParamsWithHTTPClient(client *http.Client) *QuoteCartTotalManagementV1CollectTotalsPutMineParams {
	var ()
	return &QuoteCartTotalManagementV1CollectTotalsPutMineParams{
		HTTPClient: client,
	}
}

/*QuoteCartTotalManagementV1CollectTotalsPutMineParams contains all the parameters to send to the API endpoint
for the quote cart total management v1 collect totals put mine operation typically these are written to a http.Request
*/
type QuoteCartTotalManagementV1CollectTotalsPutMineParams struct {

	/*QuoteCartTotalManagementV1CollectTotalsPutBody*/
	QuoteCartTotalManagementV1CollectTotalsPutBody QuoteCartTotalManagementV1CollectTotalsPutMineBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the quote cart total management v1 collect totals put mine params
func (o *QuoteCartTotalManagementV1CollectTotalsPutMineParams) WithTimeout(timeout time.Duration) *QuoteCartTotalManagementV1CollectTotalsPutMineParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the quote cart total management v1 collect totals put mine params
func (o *QuoteCartTotalManagementV1CollectTotalsPutMineParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the quote cart total management v1 collect totals put mine params
func (o *QuoteCartTotalManagementV1CollectTotalsPutMineParams) WithContext(ctx context.Context) *QuoteCartTotalManagementV1CollectTotalsPutMineParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the quote cart total management v1 collect totals put mine params
func (o *QuoteCartTotalManagementV1CollectTotalsPutMineParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the quote cart total management v1 collect totals put mine params
func (o *QuoteCartTotalManagementV1CollectTotalsPutMineParams) WithHTTPClient(client *http.Client) *QuoteCartTotalManagementV1CollectTotalsPutMineParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the quote cart total management v1 collect totals put mine params
func (o *QuoteCartTotalManagementV1CollectTotalsPutMineParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithQuoteCartTotalManagementV1CollectTotalsPutBody adds the quoteCartTotalManagementV1CollectTotalsPutBody to the quote cart total management v1 collect totals put mine params
func (o *QuoteCartTotalManagementV1CollectTotalsPutMineParams) WithQuoteCartTotalManagementV1CollectTotalsPutBody(quoteCartTotalManagementV1CollectTotalsPutBody QuoteCartTotalManagementV1CollectTotalsPutMineBody) *QuoteCartTotalManagementV1CollectTotalsPutMineParams {
	o.SetQuoteCartTotalManagementV1CollectTotalsPutBody(quoteCartTotalManagementV1CollectTotalsPutBody)
	return o
}

// SetQuoteCartTotalManagementV1CollectTotalsPutBody adds the quoteCartTotalManagementV1CollectTotalsPutBody to the quote cart total management v1 collect totals put mine params
func (o *QuoteCartTotalManagementV1CollectTotalsPutMineParams) SetQuoteCartTotalManagementV1CollectTotalsPutBody(quoteCartTotalManagementV1CollectTotalsPutBody QuoteCartTotalManagementV1CollectTotalsPutMineBody) {
	o.QuoteCartTotalManagementV1CollectTotalsPutBody = quoteCartTotalManagementV1CollectTotalsPutBody
}

// WriteToRequest writes these params to a swagger request
func (o *QuoteCartTotalManagementV1CollectTotalsPutMineParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.QuoteCartTotalManagementV1CollectTotalsPutBody); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
