// Code generated by go-swagger; DO NOT EDIT.

package gift_message_cart_repository_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGiftMessageCartRepositoryV1SavePostParams creates a new GiftMessageCartRepositoryV1SavePostParams object
// with the default values initialized.
func NewGiftMessageCartRepositoryV1SavePostParams() *GiftMessageCartRepositoryV1SavePostParams {
	var ()
	return &GiftMessageCartRepositoryV1SavePostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGiftMessageCartRepositoryV1SavePostParamsWithTimeout creates a new GiftMessageCartRepositoryV1SavePostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGiftMessageCartRepositoryV1SavePostParamsWithTimeout(timeout time.Duration) *GiftMessageCartRepositoryV1SavePostParams {
	var ()
	return &GiftMessageCartRepositoryV1SavePostParams{

		timeout: timeout,
	}
}

// NewGiftMessageCartRepositoryV1SavePostParamsWithContext creates a new GiftMessageCartRepositoryV1SavePostParams object
// with the default values initialized, and the ability to set a context for a request
func NewGiftMessageCartRepositoryV1SavePostParamsWithContext(ctx context.Context) *GiftMessageCartRepositoryV1SavePostParams {
	var ()
	return &GiftMessageCartRepositoryV1SavePostParams{

		Context: ctx,
	}
}

// NewGiftMessageCartRepositoryV1SavePostParamsWithHTTPClient creates a new GiftMessageCartRepositoryV1SavePostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGiftMessageCartRepositoryV1SavePostParamsWithHTTPClient(client *http.Client) *GiftMessageCartRepositoryV1SavePostParams {
	var ()
	return &GiftMessageCartRepositoryV1SavePostParams{
		HTTPClient: client,
	}
}

/*GiftMessageCartRepositoryV1SavePostParams contains all the parameters to send to the API endpoint
for the gift message cart repository v1 save post operation typically these are written to a http.Request
*/
type GiftMessageCartRepositoryV1SavePostParams struct {

	/*CartID
	  The cart ID.

	*/
	CartID int64
	/*GiftMessageCartRepositoryV1SavePostBody*/
	GiftMessageCartRepositoryV1SavePostBody GiftMessageCartRepositoryV1SavePostBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the gift message cart repository v1 save post params
func (o *GiftMessageCartRepositoryV1SavePostParams) WithTimeout(timeout time.Duration) *GiftMessageCartRepositoryV1SavePostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the gift message cart repository v1 save post params
func (o *GiftMessageCartRepositoryV1SavePostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the gift message cart repository v1 save post params
func (o *GiftMessageCartRepositoryV1SavePostParams) WithContext(ctx context.Context) *GiftMessageCartRepositoryV1SavePostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the gift message cart repository v1 save post params
func (o *GiftMessageCartRepositoryV1SavePostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the gift message cart repository v1 save post params
func (o *GiftMessageCartRepositoryV1SavePostParams) WithHTTPClient(client *http.Client) *GiftMessageCartRepositoryV1SavePostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the gift message cart repository v1 save post params
func (o *GiftMessageCartRepositoryV1SavePostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCartID adds the cartID to the gift message cart repository v1 save post params
func (o *GiftMessageCartRepositoryV1SavePostParams) WithCartID(cartID int64) *GiftMessageCartRepositoryV1SavePostParams {
	o.SetCartID(cartID)
	return o
}

// SetCartID adds the cartId to the gift message cart repository v1 save post params
func (o *GiftMessageCartRepositoryV1SavePostParams) SetCartID(cartID int64) {
	o.CartID = cartID
}

// WithGiftMessageCartRepositoryV1SavePostBody adds the giftMessageCartRepositoryV1SavePostBody to the gift message cart repository v1 save post params
func (o *GiftMessageCartRepositoryV1SavePostParams) WithGiftMessageCartRepositoryV1SavePostBody(giftMessageCartRepositoryV1SavePostBody GiftMessageCartRepositoryV1SavePostBody) *GiftMessageCartRepositoryV1SavePostParams {
	o.SetGiftMessageCartRepositoryV1SavePostBody(giftMessageCartRepositoryV1SavePostBody)
	return o
}

// SetGiftMessageCartRepositoryV1SavePostBody adds the giftMessageCartRepositoryV1SavePostBody to the gift message cart repository v1 save post params
func (o *GiftMessageCartRepositoryV1SavePostParams) SetGiftMessageCartRepositoryV1SavePostBody(giftMessageCartRepositoryV1SavePostBody GiftMessageCartRepositoryV1SavePostBody) {
	o.GiftMessageCartRepositoryV1SavePostBody = giftMessageCartRepositoryV1SavePostBody
}

// WriteToRequest writes these params to a swagger request
func (o *GiftMessageCartRepositoryV1SavePostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cartId
	if err := r.SetPathParam("cartId", swag.FormatInt64(o.CartID)); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.GiftMessageCartRepositoryV1SavePostBody); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
