// Code generated by go-swagger; DO NOT EDIT.

package customer_account_management_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCustomerAccountManagementV1CreateAccountPostParams creates a new CustomerAccountManagementV1CreateAccountPostParams object
// with the default values initialized.
func NewCustomerAccountManagementV1CreateAccountPostParams() *CustomerAccountManagementV1CreateAccountPostParams {
	var ()
	return &CustomerAccountManagementV1CreateAccountPostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCustomerAccountManagementV1CreateAccountPostParamsWithTimeout creates a new CustomerAccountManagementV1CreateAccountPostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCustomerAccountManagementV1CreateAccountPostParamsWithTimeout(timeout time.Duration) *CustomerAccountManagementV1CreateAccountPostParams {
	var ()
	return &CustomerAccountManagementV1CreateAccountPostParams{

		timeout: timeout,
	}
}

// NewCustomerAccountManagementV1CreateAccountPostParamsWithContext creates a new CustomerAccountManagementV1CreateAccountPostParams object
// with the default values initialized, and the ability to set a context for a request
func NewCustomerAccountManagementV1CreateAccountPostParamsWithContext(ctx context.Context) *CustomerAccountManagementV1CreateAccountPostParams {
	var ()
	return &CustomerAccountManagementV1CreateAccountPostParams{

		Context: ctx,
	}
}

// NewCustomerAccountManagementV1CreateAccountPostParamsWithHTTPClient creates a new CustomerAccountManagementV1CreateAccountPostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCustomerAccountManagementV1CreateAccountPostParamsWithHTTPClient(client *http.Client) *CustomerAccountManagementV1CreateAccountPostParams {
	var ()
	return &CustomerAccountManagementV1CreateAccountPostParams{
		HTTPClient: client,
	}
}

/*CustomerAccountManagementV1CreateAccountPostParams contains all the parameters to send to the API endpoint
for the customer account management v1 create account post operation typically these are written to a http.Request
*/
type CustomerAccountManagementV1CreateAccountPostParams struct {

	/*CustomerAccountManagementV1CreateAccountPostBody*/
	CustomerAccountManagementV1CreateAccountPostBody CustomerAccountManagementV1CreateAccountPostBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the customer account management v1 create account post params
func (o *CustomerAccountManagementV1CreateAccountPostParams) WithTimeout(timeout time.Duration) *CustomerAccountManagementV1CreateAccountPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the customer account management v1 create account post params
func (o *CustomerAccountManagementV1CreateAccountPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the customer account management v1 create account post params
func (o *CustomerAccountManagementV1CreateAccountPostParams) WithContext(ctx context.Context) *CustomerAccountManagementV1CreateAccountPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the customer account management v1 create account post params
func (o *CustomerAccountManagementV1CreateAccountPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the customer account management v1 create account post params
func (o *CustomerAccountManagementV1CreateAccountPostParams) WithHTTPClient(client *http.Client) *CustomerAccountManagementV1CreateAccountPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the customer account management v1 create account post params
func (o *CustomerAccountManagementV1CreateAccountPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomerAccountManagementV1CreateAccountPostBody adds the customerAccountManagementV1CreateAccountPostBody to the customer account management v1 create account post params
func (o *CustomerAccountManagementV1CreateAccountPostParams) WithCustomerAccountManagementV1CreateAccountPostBody(customerAccountManagementV1CreateAccountPostBody CustomerAccountManagementV1CreateAccountPostBody) *CustomerAccountManagementV1CreateAccountPostParams {
	o.SetCustomerAccountManagementV1CreateAccountPostBody(customerAccountManagementV1CreateAccountPostBody)
	return o
}

// SetCustomerAccountManagementV1CreateAccountPostBody adds the customerAccountManagementV1CreateAccountPostBody to the customer account management v1 create account post params
func (o *CustomerAccountManagementV1CreateAccountPostParams) SetCustomerAccountManagementV1CreateAccountPostBody(customerAccountManagementV1CreateAccountPostBody CustomerAccountManagementV1CreateAccountPostBody) {
	o.CustomerAccountManagementV1CreateAccountPostBody = customerAccountManagementV1CreateAccountPostBody
}

// WriteToRequest writes these params to a swagger request
func (o *CustomerAccountManagementV1CreateAccountPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.CustomerAccountManagementV1CreateAccountPostBody); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
