// Code generated by go-swagger; DO NOT EDIT.

package customer_account_management_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCustomerAccountManagementV1ResetPasswordPostParams creates a new CustomerAccountManagementV1ResetPasswordPostParams object
// with the default values initialized.
func NewCustomerAccountManagementV1ResetPasswordPostParams() *CustomerAccountManagementV1ResetPasswordPostParams {
	var ()
	return &CustomerAccountManagementV1ResetPasswordPostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCustomerAccountManagementV1ResetPasswordPostParamsWithTimeout creates a new CustomerAccountManagementV1ResetPasswordPostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCustomerAccountManagementV1ResetPasswordPostParamsWithTimeout(timeout time.Duration) *CustomerAccountManagementV1ResetPasswordPostParams {
	var ()
	return &CustomerAccountManagementV1ResetPasswordPostParams{

		timeout: timeout,
	}
}

// NewCustomerAccountManagementV1ResetPasswordPostParamsWithContext creates a new CustomerAccountManagementV1ResetPasswordPostParams object
// with the default values initialized, and the ability to set a context for a request
func NewCustomerAccountManagementV1ResetPasswordPostParamsWithContext(ctx context.Context) *CustomerAccountManagementV1ResetPasswordPostParams {
	var ()
	return &CustomerAccountManagementV1ResetPasswordPostParams{

		Context: ctx,
	}
}

// NewCustomerAccountManagementV1ResetPasswordPostParamsWithHTTPClient creates a new CustomerAccountManagementV1ResetPasswordPostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCustomerAccountManagementV1ResetPasswordPostParamsWithHTTPClient(client *http.Client) *CustomerAccountManagementV1ResetPasswordPostParams {
	var ()
	return &CustomerAccountManagementV1ResetPasswordPostParams{
		HTTPClient: client,
	}
}

/*CustomerAccountManagementV1ResetPasswordPostParams contains all the parameters to send to the API endpoint
for the customer account management v1 reset password post operation typically these are written to a http.Request
*/
type CustomerAccountManagementV1ResetPasswordPostParams struct {

	/*CustomerAccountManagementV1ResetPasswordPostBody*/
	CustomerAccountManagementV1ResetPasswordPostBody CustomerAccountManagementV1ResetPasswordPostBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the customer account management v1 reset password post params
func (o *CustomerAccountManagementV1ResetPasswordPostParams) WithTimeout(timeout time.Duration) *CustomerAccountManagementV1ResetPasswordPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the customer account management v1 reset password post params
func (o *CustomerAccountManagementV1ResetPasswordPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the customer account management v1 reset password post params
func (o *CustomerAccountManagementV1ResetPasswordPostParams) WithContext(ctx context.Context) *CustomerAccountManagementV1ResetPasswordPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the customer account management v1 reset password post params
func (o *CustomerAccountManagementV1ResetPasswordPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the customer account management v1 reset password post params
func (o *CustomerAccountManagementV1ResetPasswordPostParams) WithHTTPClient(client *http.Client) *CustomerAccountManagementV1ResetPasswordPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the customer account management v1 reset password post params
func (o *CustomerAccountManagementV1ResetPasswordPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomerAccountManagementV1ResetPasswordPostBody adds the customerAccountManagementV1ResetPasswordPostBody to the customer account management v1 reset password post params
func (o *CustomerAccountManagementV1ResetPasswordPostParams) WithCustomerAccountManagementV1ResetPasswordPostBody(customerAccountManagementV1ResetPasswordPostBody CustomerAccountManagementV1ResetPasswordPostBody) *CustomerAccountManagementV1ResetPasswordPostParams {
	o.SetCustomerAccountManagementV1ResetPasswordPostBody(customerAccountManagementV1ResetPasswordPostBody)
	return o
}

// SetCustomerAccountManagementV1ResetPasswordPostBody adds the customerAccountManagementV1ResetPasswordPostBody to the customer account management v1 reset password post params
func (o *CustomerAccountManagementV1ResetPasswordPostParams) SetCustomerAccountManagementV1ResetPasswordPostBody(customerAccountManagementV1ResetPasswordPostBody CustomerAccountManagementV1ResetPasswordPostBody) {
	o.CustomerAccountManagementV1ResetPasswordPostBody = customerAccountManagementV1ResetPasswordPostBody
}

// WriteToRequest writes these params to a swagger request
func (o *CustomerAccountManagementV1ResetPasswordPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.CustomerAccountManagementV1ResetPasswordPostBody); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
