// Code generated by go-swagger; DO NOT EDIT.

package sales_rule_coupon_repository_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	models "flamingo.me/flamingo-commerce-adapter-magento2/magento2/infrastructure/swaggerclient/models"
)

// SalesRuleCouponRepositoryV1SavePutReader is a Reader for the SalesRuleCouponRepositoryV1SavePut structure.
type SalesRuleCouponRepositoryV1SavePutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SalesRuleCouponRepositoryV1SavePutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSalesRuleCouponRepositoryV1SavePutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewSalesRuleCouponRepositoryV1SavePutBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewSalesRuleCouponRepositoryV1SavePutUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewSalesRuleCouponRepositoryV1SavePutInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewSalesRuleCouponRepositoryV1SavePutDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSalesRuleCouponRepositoryV1SavePutOK creates a SalesRuleCouponRepositoryV1SavePutOK with default headers values
func NewSalesRuleCouponRepositoryV1SavePutOK() *SalesRuleCouponRepositoryV1SavePutOK {
	return &SalesRuleCouponRepositoryV1SavePutOK{}
}

/*SalesRuleCouponRepositoryV1SavePutOK handles this case with default header values.

200 Success.
*/
type SalesRuleCouponRepositoryV1SavePutOK struct {
	Payload *models.SalesRuleDataCouponInterface
}

func (o *SalesRuleCouponRepositoryV1SavePutOK) Error() string {
	return fmt.Sprintf("[PUT /V1/coupons/{couponId}][%d] salesRuleCouponRepositoryV1SavePutOK  %+v", 200, o.Payload)
}

func (o *SalesRuleCouponRepositoryV1SavePutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SalesRuleDataCouponInterface)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSalesRuleCouponRepositoryV1SavePutBadRequest creates a SalesRuleCouponRepositoryV1SavePutBadRequest with default headers values
func NewSalesRuleCouponRepositoryV1SavePutBadRequest() *SalesRuleCouponRepositoryV1SavePutBadRequest {
	return &SalesRuleCouponRepositoryV1SavePutBadRequest{}
}

/*SalesRuleCouponRepositoryV1SavePutBadRequest handles this case with default header values.

400 Bad Request
*/
type SalesRuleCouponRepositoryV1SavePutBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *SalesRuleCouponRepositoryV1SavePutBadRequest) Error() string {
	return fmt.Sprintf("[PUT /V1/coupons/{couponId}][%d] salesRuleCouponRepositoryV1SavePutBadRequest  %+v", 400, o.Payload)
}

func (o *SalesRuleCouponRepositoryV1SavePutBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSalesRuleCouponRepositoryV1SavePutUnauthorized creates a SalesRuleCouponRepositoryV1SavePutUnauthorized with default headers values
func NewSalesRuleCouponRepositoryV1SavePutUnauthorized() *SalesRuleCouponRepositoryV1SavePutUnauthorized {
	return &SalesRuleCouponRepositoryV1SavePutUnauthorized{}
}

/*SalesRuleCouponRepositoryV1SavePutUnauthorized handles this case with default header values.

401 Unauthorized
*/
type SalesRuleCouponRepositoryV1SavePutUnauthorized struct {
	Payload *models.ErrorResponse
}

func (o *SalesRuleCouponRepositoryV1SavePutUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /V1/coupons/{couponId}][%d] salesRuleCouponRepositoryV1SavePutUnauthorized  %+v", 401, o.Payload)
}

func (o *SalesRuleCouponRepositoryV1SavePutUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSalesRuleCouponRepositoryV1SavePutInternalServerError creates a SalesRuleCouponRepositoryV1SavePutInternalServerError with default headers values
func NewSalesRuleCouponRepositoryV1SavePutInternalServerError() *SalesRuleCouponRepositoryV1SavePutInternalServerError {
	return &SalesRuleCouponRepositoryV1SavePutInternalServerError{}
}

/*SalesRuleCouponRepositoryV1SavePutInternalServerError handles this case with default header values.

Internal Server error
*/
type SalesRuleCouponRepositoryV1SavePutInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *SalesRuleCouponRepositoryV1SavePutInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /V1/coupons/{couponId}][%d] salesRuleCouponRepositoryV1SavePutInternalServerError  %+v", 500, o.Payload)
}

func (o *SalesRuleCouponRepositoryV1SavePutInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSalesRuleCouponRepositoryV1SavePutDefault creates a SalesRuleCouponRepositoryV1SavePutDefault with default headers values
func NewSalesRuleCouponRepositoryV1SavePutDefault(code int) *SalesRuleCouponRepositoryV1SavePutDefault {
	return &SalesRuleCouponRepositoryV1SavePutDefault{
		_statusCode: code,
	}
}

/*SalesRuleCouponRepositoryV1SavePutDefault handles this case with default header values.

Unexpected error
*/
type SalesRuleCouponRepositoryV1SavePutDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the sales rule coupon repository v1 save put default response
func (o *SalesRuleCouponRepositoryV1SavePutDefault) Code() int {
	return o._statusCode
}

func (o *SalesRuleCouponRepositoryV1SavePutDefault) Error() string {
	return fmt.Sprintf("[PUT /V1/coupons/{couponId}][%d] salesRuleCouponRepositoryV1SavePut default  %+v", o._statusCode, o.Payload)
}

func (o *SalesRuleCouponRepositoryV1SavePutDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*SalesRuleCouponRepositoryV1SavePutBody sales rule coupon repository v1 save put body
swagger:model SalesRuleCouponRepositoryV1SavePutBody
*/
type SalesRuleCouponRepositoryV1SavePutBody struct {

	// coupon
	// Required: true
	Coupon *models.SalesRuleDataCouponInterface `json:"coupon"`
}

// Validate validates this sales rule coupon repository v1 save put body
func (o *SalesRuleCouponRepositoryV1SavePutBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCoupon(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SalesRuleCouponRepositoryV1SavePutBody) validateCoupon(formats strfmt.Registry) error {

	if err := validate.Required("salesRuleCouponRepositoryV1SavePutBody"+"."+"coupon", "body", o.Coupon); err != nil {
		return err
	}

	if o.Coupon != nil {
		if err := o.Coupon.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("salesRuleCouponRepositoryV1SavePutBody" + "." + "coupon")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *SalesRuleCouponRepositoryV1SavePutBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SalesRuleCouponRepositoryV1SavePutBody) UnmarshalBinary(b []byte) error {
	var res SalesRuleCouponRepositoryV1SavePutBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
