// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// BundleDataOptionTypeInterface Interface OptionTypeInterface
// swagger:model bundle-data-option-type-interface
type BundleDataOptionTypeInterface struct {

	// Type code
	// Required: true
	Code *string `json:"code"`

	// extension attributes
	ExtensionAttributes BundleDataOptionTypeExtensionInterface `json:"extension_attributes,omitempty"`

	// Type label
	// Required: true
	Label *string `json:"label"`
}

// Validate validates this bundle data option type interface
func (m *BundleDataOptionTypeInterface) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLabel(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BundleDataOptionTypeInterface) validateCode(formats strfmt.Registry) error {

	if err := validate.Required("code", "body", m.Code); err != nil {
		return err
	}

	return nil
}

func (m *BundleDataOptionTypeInterface) validateLabel(formats strfmt.Registry) error {

	if err := validate.Required("label", "body", m.Label); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *BundleDataOptionTypeInterface) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BundleDataOptionTypeInterface) UnmarshalBinary(b []byte) error {
	var res BundleDataOptionTypeInterface
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
