// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CatalogDataBasePriceInterface Price interface.
// swagger:model catalog-data-base-price-interface
type CatalogDataBasePriceInterface struct {

	// extension attributes
	ExtensionAttributes CatalogDataBasePriceExtensionInterface `json:"extension_attributes,omitempty"`

	// Price.
	// Required: true
	Price *float64 `json:"price"`

	// SKU.
	// Required: true
	Sku *string `json:"sku"`

	// Store id.
	// Required: true
	StoreID *int64 `json:"store_id"`
}

// Validate validates this catalog data base price interface
func (m *CatalogDataBasePriceInterface) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePrice(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSku(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStoreID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CatalogDataBasePriceInterface) validatePrice(formats strfmt.Registry) error {

	if err := validate.Required("price", "body", m.Price); err != nil {
		return err
	}

	return nil
}

func (m *CatalogDataBasePriceInterface) validateSku(formats strfmt.Registry) error {

	if err := validate.Required("sku", "body", m.Sku); err != nil {
		return err
	}

	return nil
}

func (m *CatalogDataBasePriceInterface) validateStoreID(formats strfmt.Registry) error {

	if err := validate.Required("store_id", "body", m.StoreID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CatalogDataBasePriceInterface) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CatalogDataBasePriceInterface) UnmarshalBinary(b []byte) error {
	var res CatalogDataBasePriceInterface
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
