// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// CatalogDataTierPriceExtensionInterface ExtensionInterface class for @see \Magento\Catalog\Api\Data\TierPriceInterface
// swagger:model catalog-data-tier-price-extension-interface
type CatalogDataTierPriceExtensionInterface interface{}
