// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// CheckoutDataTotalsInformationExtensionInterface ExtensionInterface class for @see \Magento\Checkout\Api\Data\TotalsInformationInterface
// swagger:model checkout-data-totals-information-extension-interface
type CheckoutDataTotalsInformationExtensionInterface interface{}
