// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CompanyCreditDataCreditDataInterface Credit Data interface.
// swagger:model company-credit-data-credit-data-interface
type CompanyCreditDataCreditDataInterface struct {

	// Available Limit.
	AvailableLimit float64 `json:"available_limit,omitempty"`

	// Balance.
	Balance float64 `json:"balance,omitempty"`

	// Company id.
	CompanyID int64 `json:"company_id,omitempty"`

	// Credit Limit.
	CreditLimit float64 `json:"credit_limit,omitempty"`

	// Currency Code.
	CurrencyCode string `json:"currency_code,omitempty"`

	// Exceed Limit.
	// Required: true
	ExceedLimit *bool `json:"exceed_limit"`

	// ID.
	ID int64 `json:"id,omitempty"`
}

// Validate validates this company credit data credit data interface
func (m *CompanyCreditDataCreditDataInterface) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateExceedLimit(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CompanyCreditDataCreditDataInterface) validateExceedLimit(formats strfmt.Registry) error {

	if err := validate.Required("exceed_limit", "body", m.ExceedLimit); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CompanyCreditDataCreditDataInterface) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CompanyCreditDataCreditDataInterface) UnmarshalBinary(b []byte) error {
	var res CompanyCreditDataCreditDataInterface
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
