// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// CustomerDataAddressExtensionInterface ExtensionInterface class for @see \Magento\Customer\Api\Data\AddressInterface
// swagger:model customer-data-address-extension-interface
type CustomerDataAddressExtensionInterface interface{}
