// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// QuoteDataCartItemExtensionInterface ExtensionInterface class for @see \Magento\Quote\Api\Data\CartItemInterface
// swagger:model quote-data-cart-item-extension-interface
type QuoteDataCartItemExtensionInterface struct {

	// negotiable quote item
	NegotiableQuoteItem *NegotiableQuoteDataNegotiableQuoteItemInterface `json:"negotiable_quote_item,omitempty"`
}

// Validate validates this quote data cart item extension interface
func (m *QuoteDataCartItemExtensionInterface) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNegotiableQuoteItem(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *QuoteDataCartItemExtensionInterface) validateNegotiableQuoteItem(formats strfmt.Registry) error {

	if swag.IsZero(m.NegotiableQuoteItem) { // not required
		return nil
	}

	if m.NegotiableQuoteItem != nil {
		if err := m.NegotiableQuoteItem.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("negotiable_quote_item")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *QuoteDataCartItemExtensionInterface) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *QuoteDataCartItemExtensionInterface) UnmarshalBinary(b []byte) error {
	var res QuoteDataCartItemExtensionInterface
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
