// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// QuoteDataCurrencyInterface Interface CurrencyInterface
// swagger:model quote-data-currency-interface
type QuoteDataCurrencyInterface struct {

	// Base currency code
	BaseCurrencyCode string `json:"base_currency_code,omitempty"`

	// Base currency to global currency rate
	BaseToGlobalRate float64 `json:"base_to_global_rate,omitempty"`

	// Base currency to quote currency rate
	BaseToQuoteRate float64 `json:"base_to_quote_rate,omitempty"`

	// extension attributes
	ExtensionAttributes QuoteDataCurrencyExtensionInterface `json:"extension_attributes,omitempty"`

	// Global currency code
	GlobalCurrencyCode string `json:"global_currency_code,omitempty"`

	// Quote currency code
	QuoteCurrencyCode string `json:"quote_currency_code,omitempty"`

	// Store currency code
	StoreCurrencyCode string `json:"store_currency_code,omitempty"`

	// Store currency to base currency rate
	StoreToBaseRate float64 `json:"store_to_base_rate,omitempty"`

	// Store currency to quote currency rate
	StoreToQuoteRate float64 `json:"store_to_quote_rate,omitempty"`
}

// Validate validates this quote data currency interface
func (m *QuoteDataCurrencyInterface) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *QuoteDataCurrencyInterface) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *QuoteDataCurrencyInterface) UnmarshalBinary(b []byte) error {
	var res QuoteDataCurrencyInterface
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
