// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// SalesDataShipmentPackageExtensionInterface ExtensionInterface class for @see \Magento\Sales\Api\Data\ShipmentPackageInterface
// swagger:model sales-data-shipment-package-extension-interface
type SalesDataShipmentPackageExtensionInterface interface{}
