// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// TaxDataTaxRuleExtensionInterface ExtensionInterface class for @see \Magento\Tax\Api\Data\TaxRuleInterface
// swagger:model tax-data-tax-rule-extension-interface
type TaxDataTaxRuleExtensionInterface interface{}
