// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// TaxDataOrderTaxDetailsItemExtensionInterface ExtensionInterface class for @see \Magento\Tax\Api\Data\OrderTaxDetailsItemInterface
// swagger:model tax-data-order-tax-details-item-extension-interface
type TaxDataOrderTaxDetailsItemExtensionInterface interface{}
