// Code generated by go-swagger; DO NOT EDIT.

package rma_rma_attributes_management_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewRmaRmaAttributesManagementV1GetAttributeMetadataGetParams creates a new RmaRmaAttributesManagementV1GetAttributeMetadataGetParams object
// with the default values initialized.
func NewRmaRmaAttributesManagementV1GetAttributeMetadataGetParams() *RmaRmaAttributesManagementV1GetAttributeMetadataGetParams {
	var ()
	return &RmaRmaAttributesManagementV1GetAttributeMetadataGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRmaRmaAttributesManagementV1GetAttributeMetadataGetParamsWithTimeout creates a new RmaRmaAttributesManagementV1GetAttributeMetadataGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRmaRmaAttributesManagementV1GetAttributeMetadataGetParamsWithTimeout(timeout time.Duration) *RmaRmaAttributesManagementV1GetAttributeMetadataGetParams {
	var ()
	return &RmaRmaAttributesManagementV1GetAttributeMetadataGetParams{

		timeout: timeout,
	}
}

// NewRmaRmaAttributesManagementV1GetAttributeMetadataGetParamsWithContext creates a new RmaRmaAttributesManagementV1GetAttributeMetadataGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewRmaRmaAttributesManagementV1GetAttributeMetadataGetParamsWithContext(ctx context.Context) *RmaRmaAttributesManagementV1GetAttributeMetadataGetParams {
	var ()
	return &RmaRmaAttributesManagementV1GetAttributeMetadataGetParams{

		Context: ctx,
	}
}

// NewRmaRmaAttributesManagementV1GetAttributeMetadataGetParamsWithHTTPClient creates a new RmaRmaAttributesManagementV1GetAttributeMetadataGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRmaRmaAttributesManagementV1GetAttributeMetadataGetParamsWithHTTPClient(client *http.Client) *RmaRmaAttributesManagementV1GetAttributeMetadataGetParams {
	var ()
	return &RmaRmaAttributesManagementV1GetAttributeMetadataGetParams{
		HTTPClient: client,
	}
}

/*RmaRmaAttributesManagementV1GetAttributeMetadataGetParams contains all the parameters to send to the API endpoint
for the rma rma attributes management v1 get attribute metadata get operation typically these are written to a http.Request
*/
type RmaRmaAttributesManagementV1GetAttributeMetadataGetParams struct {

	/*AttributeCode*/
	AttributeCode string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the rma rma attributes management v1 get attribute metadata get params
func (o *RmaRmaAttributesManagementV1GetAttributeMetadataGetParams) WithTimeout(timeout time.Duration) *RmaRmaAttributesManagementV1GetAttributeMetadataGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the rma rma attributes management v1 get attribute metadata get params
func (o *RmaRmaAttributesManagementV1GetAttributeMetadataGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the rma rma attributes management v1 get attribute metadata get params
func (o *RmaRmaAttributesManagementV1GetAttributeMetadataGetParams) WithContext(ctx context.Context) *RmaRmaAttributesManagementV1GetAttributeMetadataGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the rma rma attributes management v1 get attribute metadata get params
func (o *RmaRmaAttributesManagementV1GetAttributeMetadataGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the rma rma attributes management v1 get attribute metadata get params
func (o *RmaRmaAttributesManagementV1GetAttributeMetadataGetParams) WithHTTPClient(client *http.Client) *RmaRmaAttributesManagementV1GetAttributeMetadataGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the rma rma attributes management v1 get attribute metadata get params
func (o *RmaRmaAttributesManagementV1GetAttributeMetadataGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAttributeCode adds the attributeCode to the rma rma attributes management v1 get attribute metadata get params
func (o *RmaRmaAttributesManagementV1GetAttributeMetadataGetParams) WithAttributeCode(attributeCode string) *RmaRmaAttributesManagementV1GetAttributeMetadataGetParams {
	o.SetAttributeCode(attributeCode)
	return o
}

// SetAttributeCode adds the attributeCode to the rma rma attributes management v1 get attribute metadata get params
func (o *RmaRmaAttributesManagementV1GetAttributeMetadataGetParams) SetAttributeCode(attributeCode string) {
	o.AttributeCode = attributeCode
}

// WriteToRequest writes these params to a swagger request
func (o *RmaRmaAttributesManagementV1GetAttributeMetadataGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param attributeCode
	if err := r.SetPathParam("attributeCode", o.AttributeCode); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
